/**
 * @module Buffer
 * @license MIT
 * @version 0.0.1
 * @author nuintun
 * @description A buffer tool using WebAssembly.
 * @see https://github.com/nuintun/AssemblyBuffer#readme
 */

(function (factory) {
    typeof define === 'function' && define.amd ? define('buffer', factory) :
    factory();
}((function () { 'use strict';

    /**
     * @module hex
     */
    function zero(num, max) {
        return num.toString(16).toUpperCase().padStart(max, '0');
    }
    function hex(buffer) {
        var length = buffer.length;
        var last = length % 16 || 16;
        var rows = Math.ceil(length / 16);
        var offsetLength = Math.max(6, length.toString(16).length);
        var rowBytes;
        var index = 0;
        var rowSpaces;
        var hex = "OFFSET  ";
        for (var i = 0; i < 16; i++) {
            hex += " " + zero(i, 2);
        }
        hex += "\n";
        if (length) {
            hex += "\n";
        }
        for (var i = 0; i < rows; i++) {
            hex += zero(index, offsetLength) + "  ";
            rowBytes = i === rows - 1 ? last : 16;
            rowSpaces = 16 - rowBytes;
            for (var j = 0; j < rowBytes; j++) {
                hex += " " + zero(buffer[index++], 2);
            }
            for (var j = 0; j <= rowSpaces; j++) {
                hex += "   ";
            }
            index -= rowBytes;
            for (var j = 0; j < rowBytes; j++) {
                var byte = buffer[index++];
                hex += (byte > 31 && byte < 127) || byte > 159 ? String.fromCharCode(byte) : ".";
            }
            hex += "\n";
        }
        return hex.trim();
    }

    /*! *****************************************************************************
    Copyright (c) Microsoft Corporation.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
    REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
    INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
    LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
    PERFORMANCE OF THIS SOFTWARE.
    ***************************************************************************** */

    function __awaiter(thisArg, _arguments, P, generator) {
        function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
        return new (P || (P = Promise))(function (resolve, reject) {
            function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
            function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
            function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
            step((generator = generator.apply(thisArg, _arguments || [])).next());
        });
    }

    function __generator(thisArg, body) {
        var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
        return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
        function verb(n) { return function (v) { return step([n, v]); }; }
        function step(op) {
            if (f) throw new TypeError("Generator is already executing.");
            while (_) try {
                if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
                if (y = 0, t) op = [op[0] & 2, t.value];
                switch (op[0]) {
                    case 0: case 1: t = op; break;
                    case 4: _.label++; return { value: op[1], done: false };
                    case 5: _.label++; y = op[1]; op = [0]; continue;
                    case 7: op = _.ops.pop(); _.trys.pop(); continue;
                    default:
                        if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                        if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                        if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                        if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                        if (t[2]) _.ops.pop();
                        _.trys.pop(); continue;
                }
                op = body.call(thisArg, _);
            } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
            if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
        }
    }

    var wasm = "AGFzbQEAAAABWRBgAn9/AGABfwF/YAJ/fwF/YAN/f38AYAF/AGAAAGADf39/AX9gBH9/f38AYAN/fn8AYAJ/fwF+YAN/fX8AYAN/fH8AYAABf2ABfgF+YAJ/fwF9YAJ/fwF8Ag0BA2VudgVhYm9ydAAHA3BvAAABAQEFAAAEAwQEAQAAAAMFDAICAAAAAgMCAwACAAABAAAAAQEBDQEBAwEEBQQEBAUFAAEBAwAGAQAABgECAQICBwMBAgIBAgYBAAEAAQEAAAAAAAADAwMDCAgKCwcDAQEBAgICAgkJDg8CBgEEBQMBAAEGUQ9/AUEAC38BQYAIC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38AQQQLfwBBBQt/AEHAwAALfwFBjMEBCwfUBi8OVUlOVDhfQVJSQVlfSUQDCwZCdWZmZXIDDAVfX25ldwAZBV9fcGluACwHX191bnBpbgAtCV9fY29sbGVjdAAuC19fcnR0aV9iYXNlAw0GbWVtb3J5AgAUX19zZXRBcmd1bWVudHNMZW5ndGgAMRJCdWZmZXIjY29uc3RydWN0b3IAShFCdWZmZXIjZ2V0Om9mZnNldABLEUJ1ZmZlciNzZXQ6b2Zmc2V0AEwRQnVmZmVyI2dldDpsZW5ndGgATRFCdWZmZXIjc2V0Omxlbmd0aABOEUJ1ZmZlciNnZXQ6YnVmZmVyAE8QQnVmZmVyI2dldDpieXRlcwBQDEJ1ZmZlciNhbGxvYwBREUJ1ZmZlciNzdGVwT2Zmc2V0AFIRQnVmZmVyI2Fzc2VydFJlYWQAUxBCdWZmZXIjd3JpdGVJbnQ4AFQRQnVmZmVyI3dyaXRlVWludDgAVRNCdWZmZXIjd3JpdGVCb29sZWFuAFYRQnVmZmVyI3dyaXRlSW50MTYAVxJCdWZmZXIjd3JpdGVVaW50MTYAWBFCdWZmZXIjd3JpdGVJbnQzMgBZEkJ1ZmZlciN3cml0ZVVpbnQzMgBaEUJ1ZmZlciN3cml0ZUludDY0AFsSQnVmZmVyI3dyaXRlVWludDY0AFwTQnVmZmVyI3dyaXRlRmxvYXQzMgBdE0J1ZmZlciN3cml0ZUZsb2F0NjQAXhFCdWZmZXIjd3JpdGVCeXRlcwBfDEJ1ZmZlciN3cml0ZQBgD0J1ZmZlciNyZWFkSW50OABhEEJ1ZmZlciNyZWFkVWludDgAYhJCdWZmZXIjcmVhZEJvb2xlYW4AYxBCdWZmZXIjcmVhZEludDE2AGQRQnVmZmVyI3JlYWRVaW50MTYAZRBCdWZmZXIjcmVhZEludDMyAGYRQnVmZmVyI3JlYWRVaW50MzIAZxBCdWZmZXIjcmVhZEludDY0AGgRQnVmZmVyI3JlYWRVaW50NjQAaRJCdWZmZXIjcmVhZEZsb2F0MzIAahJCdWZmZXIjcmVhZEZsb2F0NjQAaxBCdWZmZXIjcmVhZEJ5dGVzAGwLQnVmZmVyI3JlYWQAbQ9CdWZmZXIjdG9TdHJpbmcAbgxCdWZmZXIjY2xlYXIAbwgBMgq7a28JACAAIAE2AgQLCQAgACABNgIICxAAIAAgABABIAAgABACIAALCgAgACgCBEF8cQsKACAAKAIEQQNxC3oBAn9BkA0QDEGQDxAMQdA+EAxB0AsQDEHQPxAMQZDAABAMQcAREAxBoAgQDEHgCBAMQaAJEAxBkAoQDEGgCxAMIwQiARAEIQADQCAAIAFHBEAgABAFQQNHBEBBAEGQDEGfAUEQEAAACyAAQRRqEDAgABAEIQAMAQsLCxEAIAAgASAAKAIEQXxxchABCxEAIAAgASAAKAIEQQNxchABC1MBAX8gABAEIgFFBEBBACAAQYzBAUkgACgCCBtFBEBBAEGQDEH/AEESEAAACw8LIAAoAggiAEUEQEEAQZAMQYMBQRAQAAALIAEgABACIAAgARAICyYBAX8gASgCCCEDIAAgASACchABIAAgAxACIAMgABAIIAEgABACC38BAn8gACMFRgRAIAAoAggiAUUEQEEAQZAMQZMBQR4QAAALIAEkBQsgABAJIwYhAiAAIgEoAgwiAEEBTQR/QQEFIABBwMAAKAIASwRAQZANQdANQRZBHBAAAAsgAEEDdEHEwABqKAIAQSBxCwR/IwdFBUECCyEAIAEgAiAAEAoLIwAgAEUEQA8LIABBFGsiABAFIwdGBEAgABALIwNBAWokAwsLDQAgACgCAEF8cUEEagsJACAAIAE2AgALkgIBBH8gASgCACICQQFxRQRAQQBBoA5BkQJBDhAAAAsgAkF8cSICQfz///8DSUEAIAJBDE8bRQRAQQBBoA5BkwJBDhAAAAsgAkGAAkkEQCACQQR2IQIFIAJBHyACZ2siA0EEa3ZBEHMhAiADQQdrIQMLIAJBEElBACADQRdJG0UEQEEAQaAOQaACQQ4QAAALIAEoAgghBCABKAIEIgUEQCAFIAQQAgsgBARAIAQgBRABCyABIAAgAiADQQR0akECdGooAmBGBEAgACACIANBBHRqQQJ0aiAENgJgIARFBEAgACADQQJ0aiIEKAIEQX4gAndxIQEgBCABNgIEIAFFBEAgACAAKAIAQX4gA3dxEA4LCwsL+AMBB38gAUUEQEEAQaAOQckBQQ4QAAALIAEoAgAiBEEBcUUEQEEAQaAOQcsBQQ4QAAALIAFBBGogASgCAEF8cWoiBSgCACICQQFxBEAgBEF8cUEEaiACQXxxaiIDQfz///8DSQRAAn8gACAFEA8gASADIARBA3FyIgQQDiABQQRqIAEoAgBBfHFqIgUoAgALIQILCyAEQQJxBEACfyABQQRrKAIAIgMoAgAiB0EBcUUEQEEAQaAOQeABQRAQAAALIAdBfHFBBGogBEF8cWoiCEH8////A0kEfyAAIAMQDyADIAggB0EDcXIiBBAOIAMFIAELCyEBCyAFIAJBAnIQDiAEQXxxIgNB/P///wNJQQAgA0EMTxtFBEBBAEGgDkHvAUEOEAAACyADIAFBBGpqIAVHBEBBAEGgDkHwAUEOEAAACyAFQQRrIAE2AgAgA0GAAkkEQCADQQR2IQMFIANBHyADZ2siBEEEa3ZBEHMhAyAEQQdrIQYLIANBEElBACAGQRdJG0UEQEEAQaAOQYACQQ4QAAALIAAgAyAGQQR0akECdGooAmAhBCABQQAQASABIAQQAiAEBEAgBCABEAELIAAgAyAGQQR0akECdGogATYCYCAAIAAoAgBBASAGdHIQDiAAIAZBAnRqIgAgACgCBEEBIAN0cjYCBAvQAQECfyABIAJLBEBBAEGgDkH9AkEOEAAACyABQRNqQXBxQQRrIQEgAkFwcSEDIAAoAqAMIgIEQCABIAJBBGpJBEBBAEGgDkGEA0EQEAAACyACIAFBEGtGBEACfyACKAIAIQQgAUEQawshAQsFIAEgAEGkDGpJBEBBAEGgDkGRA0EFEAAACwsgAyABayICQRRJBEAPCyABIARBAnEgAkEIayICQQFychAOIAFBABABIAFBABACIAIgAUEEamoiAkECEA4gACACNgKgDCAAIAEQEAuVAQECfz8AIgBBAUgEf0EBIABrQABBAEgFQQALBEAAC0GQwQFBABAOQbDNAUEANgIAA0AgAUEXSQRAIAFBAnRBkMEBakEANgIEQQAhAANAIABBEEkEQCAAIAFBBHRqQQJ0QZDBAWpBADYCYCAAQQFqIQAMAQsLIAFBAWohAQwBCwtBkMEBQbTNAT8AQRB0EBFBkMEBJAkLpgMBA38CQAJAAkACQAJAIwIOAwABAgMLQQEkAkEAJAMQBiMGJAUMAwsjB0UhASMFEAQhAANAIAAjBkcEQCAAJAUgABAFIAFHBEAgACABEAdBACQDIABBFGoQMAwFCyAAEAQhAAwBCwtBACQDEAYjBRAEIwZGBEAjDiEAA0AgAEGMwQFJBEAgACgCABAMIABBBGohAAwBCwsjBRAEIQADQCAAIwZHBEAgABAFIAFHBEAgACABEAcgAEEUahAwCyAAEAQhAAwBCwsjCCEAIwYkCCAAJAYgASQHIAAQBCQFQQIkAgsMAgsjBSIAIwZHBEAgABAEJAUgABAFIwdFRwRAQQBBkAxB5AFBFBAAAAsgAEGMwQFJBEAgAEEAEAEgAEEAEAIFIwAgABANayQAIABBBGoiAUGMwQFPBEAjCUUEQBASCyMJIQIgAUEEayEAIAFBD3FFQQAgARsEfyAAKAIAQQFxRQVBAAtFBEBBAEGgDkG1BEEDEAAACyAAIAAoAgBBAXIQDiACIAAQEAsLQQoPCyMGIwYQASMGIwYQAkEAJAILQQAPCyMDC9wBAQF/IAFBgAJJBEAgAUEEdiEBBUEfIAFBAUEbIAFna3RqQQFrIAEgAUH+////AUkbIgFnayECIAEgAkEEa3ZBEHMhASACQQdrIQILIAFBEElBACACQRdJG0UEQEEAQaAOQc4CQQ4QAAALIAAgAkECdGooAgRBfyABdHEiAQR/IAAgAWggAkEEdGpBAnRqKAJgBSAAKAIAQX8gAkEBanRxIgEEfyAAIAFoIgFBAnRqKAIEIgJFBEBBAEGgDkHbAkESEAAACyAAIAJoIAFBBHRqQQJ0aigCYAVBAAsLC+UCAQN/IAFB/P///wNPBEBB0AtBoA5BzgNBHhAAAAsgAEEMIAFBE2pBcHFBBGsgAUEMTRsiAhAUIgFFBEBBBD8AIgFBEHRBBGsgACgCoAxHdCACQQFBGyACZ2t0QQFraiACIAJB/v///wFJG2pB//8DakGAgHxxQRB2IQMgASADIAEgA0obQABBAEgEQCADQABBAEgEQAALCyAAIAFBEHQ/AEEQdBARIAAgAhAUIgFFBEBBAEGgDkH0A0EQEAAACwsgAiABKAIAQXxxSwRAQQBBoA5B9gNBDhAAAAsgACABEA8gASgCACEDIAJBBGpBD3EEQEEAQaAOQekCQQ4QAAALIANBfHEgAmsiBEEQTwRAIAEgAiADQQJxchAOIAIgAUEEamoiAiAEQQRrQQFyEA4gACACEBAFIAEgA0F+cRAOIAFBBGoiACABKAIAQXxxaiAAIAEoAgBBfHFqKAIAQX1xEA4LIAELCQAgACABNgIMCwkAIAAgATYCEAslAQF/A0AgAQRAIAAiAkEBaiEAIAJBADoAACABQQFrIQEMAQsLC6wBAQF/IABB7P///wNPBEBB0AtBkAxBhAJBHxAAAAsjACMBTwRAAkBBgBAhAgNAIAIQE2shAiMCRQRAIwCtQsgBfkLkAICnQYAIaiQBDAILIAJBAEoNAAsjACMAIwFrQYAISUEKdGokAQsLAn8gAEEQaiECIwlFBEAQEgsjCSACEBUiAgsgARAWIAIgABAXIAIjCCMHEAojACACEA1qJAAgAkEUaiIBIAAQGCABC2cBAn8CQCACIQQgACABRg0AIAAgAUkEQANAIAQEQCAAIgJBAWohACABIgNBAWohASACIAMtAAA6AAAgBEEBayEEDAELCwUDQCAEBEAgBEEBayIEIABqIAEgBGotAAA6AAAMAQsLCwsLQwECfyABIABBFGsiAigCAEF8cUEQa00EQCACIAEQFyAADwsgASACKAIMEBkiAyAAIAEgAigCECIAIAAgAUsbEBogAwtiAQF/IAFFBEAPCyAARQRAQQBBkAxBpgJBDhAAAAsgAUEUayIBEAUjB0YEQCAAQRRrIgAQBSIDIwdFRgRAIAIEQCAAEAsFIAEQCwsFIwJBAUZBACADQQNGGwRAIAEQCwsLCwsJACAAIAE7AQALJAAgACABQf//A3FKBH8gAUH//wNxIgEgACABbbebqmwFIAALCxEAIAAgATYCACAAIAFBABAcCxEAIAAgATYCECAAIAFBABAcCwoAIABBFGsoAhALEQAgACABNgIUIAAgAUEAEBwLNQAgAUEASARAQeAIQcAQQThBBxAAAAsgASAAKAIESgRAQZAKQcAQQTxBBxAAAAsgACABEAILIQAgACgCBCABIAAoAghqSARAQaAJQcAQQawBQQcQAAALCxQAIABBEHRBGHVB/wFxIABBCHRyCxIAIABBCHQgAEH//wNxQQh2cgsZACAAQYD+g3hxQQh3IABB/4H8B3FBCHhyC0MAIABCCIhC/4H8h/CfwP8AgyAAQv+B/Ifwn8D/AINCCIaEIgBCEIhC//+DgPD/P4MgAEL//4OA8P8/g0IQhoRCIIoLDQAgAEEUaygCEEEBdgv9AQEFfyAAQQh2IgFBtDRqLQAAIAFB/BdqLQAAQdYAbEH8F2ogAEH/AXEiBEEDbmotAAAgBEEDcEECdEHoLGooAgBsQQt2QQZwakECdEH0LGooAgAiAUEIdSECAkAgAUH/AXEiAUECSQ0AIAJB/wFxIQEgAkEIdiEDA0AgAQRAIAQgAyABQQF2IgJqQQF0QbQ4ai0AACIFRgR/IAIgA2pBAXRBtDhqLQABQQJ0QfQsaigCACIBQQh1IQIgAUH/AXEiAUECSQ0DIABBAWsPBSAEIAVJBH8gAgUgAiADaiEDIAEgAmsLCyEBDAELCyAADwsgACACQQAgAUEBc2txagusAgECfyAAIAFBAXRqIQMgAiEBA0AgACADSQRAIAAvAQAiAkGAAUkEfyABIAI6AAAgAUEBagUgAkGAEEkEfyABIAJBBnZBwAFyIAJBP3FBgAFyQQh0cjsBACABQQJqBSADIABBAmpLQQAgAkGA+ANxQYCwA0YbBEAgAC8BAiIEQYD4A3FBgLgDRgRAIAEgAkH/B3FBCnRBgIAEaiAEQf8HcXIiAkE/cUGAAXJBGHQgAkEGdkE/cUGAAXJBEHRyIAJBDHZBP3FBgAFyQQh0ciACQRJ2QfABcnI2AgAgAUEEaiEBIABBBGohAAwFCwsgASACQQx2QeABciACQQZ2QT9xQYABckEIdHI7AQAgASACQT9xQYABcjoAAiABQQNqCwshASAAQQJqIQAMAQsLCzQBAX8gAARAIABBFGsiARAFQQNGBEBB0D9BkAxB0QJBBxAAAAsgARAJIAEjBEEDEAoLIAALQAAgAEUEQA8LIABBFGsiABAFQQNHBEBBkMAAQZAMQd8CQQUQAAALIwJBAUYEQCAAEAsFIAAQCSAAIwgjBxAKCws5ACMCQQBKBEADQCMCBEAQExoMAQsLCxATGgNAIwIEQBATGgwBCwsjAK1CyAF+QuQAgKdBgAhqJAELEAAgACgCACIABEAgABAMCwuWAQEDfwJAAkACQAJAAkACQAJAAkAgAEEIaygCAA4JAAEGAgcDBgcEBQsPCw8LIAAoAgQiASAAKAIMQQJ0aiECA0AgASACSQRAIAEoAgAiAwRAIAMQDAsgAUEEaiEBDAELCyAAKAIAEAwPCyAAKAIQIgEEQCABEAwLIAAoAhQiAARAIAAQDAsPCw8LAAsgABAvDwsgABAvCwYAIAAkCguJAQECfyMOQQhrJA4QMyMOQgA3AwBBwAwQAyQEQeAMEAMkBkHwDRADJAgDQCAAQYACSARAIw5BoAs2AgBBASQKIw5BBGskDhAzIw5BADYCACMOQQJBARAZIgE2AgAgASAAOwEAIw5BBGokDiMOIAE2AgQgACABEDQgAEEBaiEADAELCyMOQQhqJA4LGwAjDkGMwQBIBEBBoMEBQdDBAUEBQQEQAAALC+YBAQV/Iw5BCGskDhAzIw5CADcDACAAQawLKAIATwRAIABBAEgEQEGQDUHgDkHsAEEWEAAACyAAQQFqIgMhAiADQagLKAIAIgRBAnZLBEAgAkH/////AEsEQEGQD0HgDkEOQTAQAAALIARBoAsoAgAiBiACQQJ0IgUQGyICaiAFIARrEBggAiAGRwRAQaALIAI2AgBBpAsgAjYCAEGgCyACQQAQHAtBqAsgBTYCAAtBoAsgAxAWCyMOQaALNgIAIw4gATYCBEGkCygCACAAQQJ0aiABNgIAQaALIAFBARAcIw5BCGokDgu2AQEDfyMOQQhrJA4QMyMOQgA3AwAjDkEMQQQQGSIBNgIAIw4gATYCBCMOIQMjDkEIayQOEDMjDkIANwMAIAFFBEAjDkEMQQIQGSIBNgIACyABQQAQHyABQQAQASABQQAQAiAAQfz///8DSwRAQZAPQcAPQRJBORAAAAsjDiAAQQAQGSICNgIEIAIgABAYIAEgAhAfIAEgAhABIAEgABACIw5BCGokDiADIAE2AgAjDkEIaiQOIAELrwEBAn8jDkEEayQOEDMjDkEANgIAAkACQAJAIwpBAWsOAwEBAgALAAsjDiAANgIAIAAQISECCyMOQQhrJA4QMyMOQgA3AwAjDkEMQQYQGSIBNgIAIAFBABAfIAFBABABIAFBABACIw4gADYCBCAAECEgAkkgAkH8////A0tyBEBBkA9BgBBBGUEHEAAACyABIAAQHyABIAAQASABIAIQAiMOQQhqJA4jDkEEaiQOIAELiwEBAX8jDkEMayQOEDMjDkIANwMAIw5BADYCCCMOIAA2AgAjDiABNgIEIAJBAEgEQEGQDUGAEUHIDkETEAAACyMOIAE2AgggASgCCCEDIw4gADYCCCAAKAIIIAIgA2pIBEBBkA1BgBFByQ5BLxAAAAsgAiAAKAIEaiABKAIEIAEoAggQGiMOQQxqJA4LsAEBAn8jDkEMayQOEDMjDkIANwMAIw5BADYCCCABQQBKBEAjDiAANgIAIAAoAgghAiMOIAAoAhAiAzYCACABIAJqIgIgAygCCEoEQCMOIAIgAC8BABAeEDUiATYCBCMOIAE2AgAjDiAAKAIQIgM2AgggASADQQAQNyAAIAEQICMOIAEoAgAiATYCCEEBJAogACABEDYQIgsgAiAAKAIESgRAIAAgAhABCwsjDkEMaiQOC6gBAQF/Iw5BDGskDhAzIw5CADcDACMOQQA2AggjDiAANgIAIw4gADYCBCAAKAIIIQMgAUEASAR/IAEgA2oiAUEAIAFBAEobBSABIAMgASADSBsLIQEjDiACQQBIBH8gAiADaiICQQAgAkEAShsFIAIgAyACIANIGwsgAWsiAkEAIAJBAEobIgIQNSIDNgIIIAMoAgQgASAAKAIEaiACEBojDkEMaiQOIAMLNgEBfyMOQQRrJA4QMyMOQQA2AgAjDiAAKAIQIgE2AgAgAUEAIAAoAgQQOSEAIw5BBGokDiAACywAIw5BBGskDhAzIw5BADYCACMOIAA2AgAgACABIAAoAghqECMjDkEEaiQOC2wBAn8jDkEEayQOEDMjDkEANgIAIw4gADYCACAAQQEQOCMOIAAoAhQiAjYCACAAKAIIIgMgAigCCE8EQEGQDUGAEEGAAUEyEAAACyADIAIoAgRqIAE6AAAjDiAANgIAIABBARA7Iw5BBGokDgvDAQECfyMOQQxrJA4QMyMOQgA3AwAjDkEANgIIIw4gACIDNgIAIw4gADYCBCAAKAIIIQQgAUEASAR/IAEgBGoiAEEAIABBAEobBSABIAQgASAESBsLIQAgAkEASAR/IAIgBGoiAUEAIAFBAEobBSACIAQgAiAESBsLIQIjDkEMQQQQGSIBNgIIIAEgAygCACIENgIAIAEgBEEAEBwgASAAIAMoAgRqNgIEIAEgAiAAIAAgAkgbIABrNgIIIw5BDGokDiABC78EAQp/Iw5BCGskDhAzIw5CADcDACMOIAAiATYCACABECkiBkUEQCMOQQhqJA4gAQ8LIw4gBkEGbEEBEBkiCDYCBCMOQcARNgIAQcARECkhAwNAIAYgB0sEQCAAIAdBAXRqLwEAIgFBB3YEQAJAIAcgBkEBa0lBACABQf+vA2tBgQhJGwRAIAAgB0EBdGovAQIiCkH/twNrQYEISQRAIAdBAWohByAKQf8HcSABIgJB/wdxQQp0ckGAgARqIgFBgIAITwRAIAggCUEBdGogAiAKQRB0cjYCACAJQQFqIQkMAwsLCyABQdDJAGtBGU0EQCAIIAlBAXRqIAFBGms7AQAFIAFB3wFrQbj0A00EfyADIQJBACEFAkADQCACIAVOBEAgAiAFakEDdkECdCIKQQF0QcARai8BACABayIERQ0CIARBH3YEQCAKQQRqIQUFIApBBGshAgsMAQsLQX8hCgsgCgVBfwsiAkF/cwRAIAJBAXRBwBFqIgovAQYhASAIIAlBAXRqIgIgCigCAjYCACACIAE7AQQgCSABQQBHQQFqaiEJBSABECpB////AHEiAUGAgARJBEAgCCAJQQF0aiABOwEABSAIIAlBAXRqIAFBgIAEayIBQf8HcUGAuANyQRB0IAFBCnZBgLADcnI2AgAgCUEBaiEJCwsLCwUgCCAJQQF0aiABIAFB4QBrQRpJQQV0QX9zcTsBAAsgB0EBaiEHIAlBAWohCQwBCwsgCCAJQQF0EBshACMOQQhqJA4gAAu7AQEDfyMOQQhrJA4QMyMOQgA3AwAgACABRgRAIw5BCGokDkEBDwsCQCABRUEBIAAbDQAjDiAANgIAIAAQKSECIw4gATYCACABECkgAkcNACMOIAA2AgAjDiABNgIEAn8gACEDIAIhAANAIAAiAkEBayEAIAIEQCADLwEAIgIgAS8BACIERwRAIAIgBGsMAwsgA0ECaiEDIAFBAmohAQwBCwtBAAshACMOQQhqJA4gAEUPCyMOQQhqJA5BAAvRAQEFfyMOQQhrJA4QMyMOQgA3AwAjDiAANgIAIw4hBSAAIQEgACAAQRRrKAIQaiEDA0AgASADSQRAIAEvAQAiBEGAAUkEfyACQQFqBSAEQYAQSQR/IAJBAmoFIAMgAUECaktBACAEQYD4A3FBgLADRhsEQCABLwECQYD4A3FBgLgDRgRAIAJBBGohAiABQQRqIQEMBQsLIAJBA2oLCyECIAFBAmohAQwBCwsgBSACQQAQGSICNgIEIw4gADYCACAAIAAQKSACECsjDkEIaiQOIAILwQEBA38jDkEIayQOEDMjDkIANwMAIw4gAEGgPSAAGyIANgIAIw4gATYCBCMOQQxrJA4QMyMOQgA3AwAjDkEANgIIIAFFBEACfyMOQaA9NgIAQaA9CyEBCyMOIAA2AgQgABApQQF0IQMjDiABNgIEAkAgAyABEClBAXQiBGoiAkUEQCMOQQxqJA5BwD0hAgwBCyMOIAJBARAZIgI2AgggAiAAIAMQGiACIANqIAEgBBAaIw5BDGokDgsjDkEIaiQOIAILoAIBAX8jDkEMayQOEDMjDkIANwMAIw5BADYCCCMOIAE2AgAjDiABED4iAjYCBCMOIAI2AgAjDkHgOzYCCCACQeA7ED8Ef0EBBSMOIAI2AgAjDkGAPDYCCCACQYA8ED8LBEAjDiAANgIAIAAQQCEAIw5BDGokDiAADwsjDiACNgIAIw5BoDw2AgggAkGgPBA/BH9BAQUjDiACNgIAIw5BwDw2AgggAkHAPBA/CwRAIw4gADYCACMOQQhrJA4QMyMOQgA3AwAjDiAANgIAIw4gABAhQQAQGSIBNgIEIw4gADYCACABIAAgABApQQF0EBojDkEIaiQOIw5BDGokDiABDwsjDkHgPDYCACMOIAE2AghB4DwgARBBQeA9QRdBAxAAAAvDAQAjDkEEayQOEDMjDkEANgIAAkACQAJAAkAjCkEBaw4DAQIDAAsAC0EAIQILIw4gATYCACABKAIIIQMLIw5BDGskDhAzIw5CADcDACMOQQA2AggjDiABNgIAIw4gASACIAMQPSIBNgIEIw4gATYCACABKAIIIgJBAEoEQCMOIAA2AgAgACACEDgjDiAAKAIQIgM2AgAjDiABNgIIIAMgASAAKAIIEDcjDiAANgIAIAAgAhA7CyMOQQxqJA4jDkEEaiQOC8IBAQF/Iw5BFGskDhAzIw5CADcDACMOQgA3AwgjDkEANgIQIw4gADYCACMOIAE2AgwjDiACNgIQIAEgAhBCIQEjDiABNgIIQQEkCiMOQQxrJA4QMyMOQgA3AwAjDkEANgIIIw4gATYCACMOIAE2AgQgARAhIQMjDkEMQQQQGSICNgIIIAIgATYCACACIAFBABAcIAIgAzYCCCACIAE2AgQjDkEMaiQOIw4gAjYCBEEBJAogACACQQBBABBDIw5BFGokDgtuAQJ/Iw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEEBECQjDiAAKAIUIgE2AgAgACgCCCICIAEoAghPBEBBkA1BgBBByABBMhAAAAsgAiABKAIEai0AACEBIw4gADYCACAAQQEQOyMOQQRqJA4gAQtyAQJ/Iw5BCGskDhAzIw5CADcDACABQQBOBEAgASAAKAIIaiICIAAoAgRMBEAjDiAAKAIQIgM2AgAjDiADIAAoAgggAhA5IgI2AgQjDiAANgIAIAAgARA7Iw5BCGokDiACDwsLQaAJQcAQQf8DQQUQAAAL1gIBAX8jDkEMayQOEDMjDkIANwMAIw5BADYCCCMOIAE2AgAjDiABED4iAjYCBCMOIAI2AgAjDkHgOzYCCCACQeA7ED8Ef0EBBSMOIAI2AgAjDkGAPDYCCCACQYA8ED8LBEAjDiAANgIAIw5BBGskDhAzIw5BADYCACMOIAA2AgAgACAAECEQSSEAIw5BBGokDiMOQQxqJA4gAA8LIw4gAjYCACMOQaA8NgIIIAJBoDwQPwR/QQEFIw4gAjYCACMOQcA8NgIIIAJBwDwQPwsEQCMOIAA2AgAjDkEEayQOEDMjDkEANgIAIw4gADYCACAAECEhASMOQQRrJA4QMyMOQQA2AgAjDiABQX5xIgJBARAZIgE2AgAgASAAIAIQGiMOQQRqJA4jDkEEaiQOIw5BDGokDiABDwsjDkHgPDYCACMOIAE2AghB4DwgARBBQeA9QSxBAxAAAAubAgEFfyMOQRhrJA4QMyMOQgA3AwAjDkIANwMIIw5CADcDEEHAPSECIw5BwD02AgAjDiAANgIEIw4gABA6IgE2AggjDiABNgIEIAEoAgghBANAIAMgBEgEQCMOIQUjDiACNgIEIw5BoAs2AhAjDiABNgIUIAMgASgCCE8EQEGQDUGAEUGfAUEtEAAACyADIAEoAgRqLQAAIQAjDkEEayQOEDMjDkEANgIAIABBrAsoAgBPBEBBkA1B4A5B3ABBKhAAAAsjDkGkCygCACAAQQJ0aigCACIANgIAIABFBEBB0D5B4A5B4ABBKBAAAAsjDkEEaiQOIw4gADYCDCAFIAIgABBBIgI2AgAgA0EBaiEDDAELCyMOQRhqJA4gAgvmAgEFfyMOQQRrJA4QMyMOQQA2AgAgACAAIAFqIgRLBEBBAEGgPkHtBUEHEAAACyMOIAFBAXRBARAZIgI2AgAgAiEBA0AgACAESQRAAkAgAC0AACEDIABBAWohACADQYABcQRAIAAgBEYNASAALQAAQT9xIQUgAEEBaiEAIANB4AFxQcABRgRAIAEgBSADQR9xQQZ0cjsBAAUgACAERg0CIAAtAABBP3EhBiAAQQFqIQAgA0HwAXFB4AFGBEAgBiADQQ9xQQx0IAVBBnRyciEDBSAAIARGDQMgAC0AAEE/cSADQQdxQRJ0IAVBDHRyIAZBBnRyciEDIABBAWohAAsgA0GAgARJBEAgASADOwEABSABIANBgIAEayIDQQp2QYCwA3IgA0H/B3FBgLgDckEQdHI2AgAgAUECaiEBCwsFIAEgAzsBAAsgAUECaiEBDAILCwsgAiABIAJrEBshACMOQQRqJA4gAAu9AQAjDkEEayQOEDMjDiAANgIAAkACQAJAAkAjCg4DAQIDAAsAC0EAIQELQYAgIQILIw5BCGskDhAzIw5CADcDACAARQRAIw5BGEEFEBkiADYCAAsgAEEAEB0gAEEAEAEgAEEAEAIgAEEAEBYgAEEAECAgAEEAECIgACACEB0gACABIAIQHhAWIAAgACgCDBA1ECAjDiAAKAIQKAIAIgE2AgRBASQKIAAgARA2ECIjDkEIaiQOIw5BBGokDiAACyIAIw5BBGskDhAzIw4gADYCACAAKAIIIQAjDkEEaiQOIAALHwAjDkEEayQOEDMjDiAANgIAIAAgARAjIw5BBGokDgsiACMOQQRrJA4QMyMOIAA2AgAgACgCBCEAIw5BBGokDiAAC4oBAQF/Iw5BBGskDhAzIw4gADYCACMOQQRrJA4QMyMOQQA2AgAgAUEASARAQaAIQcAQQdUAQQcQAAALIw4gACgCECICNgIAIAEgAigCCEoEQCMOIAA2AgAgACABIAAoAghrEDgFIAAgARABCyABIAAoAghIBEAgACABEAILIw5BBGokDiMOQQRqJA4LvwEBA38jDkEEayQOEDMjDiAANgIAIw5BBGskDhAzIw5BADYCACMOIAAoAhAoAgAiAjYCACAAKAIEIQAjDkEIayQOEDMjDkIANwMAIw4gAjYCAEEAIAIQISIBIAFBAEobIQMjDiAAQQBIBH8gACABaiIAQQAgAEEAShsFIAAgASAAIAFIGwsgA2siAEEAIABBAEobIgFBABAZIgA2AgQgACACIANqIAEQGiMOQQhqJA4jDkEEaiQOIw5BBGokDiAACyEAIw5BBGskDhAzIw4gADYCACAAEDohACMOQQRqJA4gAAsfACMOQQRrJA4QMyMOIAA2AgAgACABEDgjDkEEaiQOCx8AIw5BBGskDhAzIw4gADYCACAAIAEQOyMOQQRqJA4LHwAjDkEEayQOEDMjDiAANgIAIAAgARAkIw5BBGokDguHAQECfyMOQQRrJA4QMyMOIAA2AgAgASECIw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEEBEDgjDiAAKAIUIgE2AgAgACgCCCIDIAEoAghPBEBBkA1BgBBB7QBBMhAAAAsgAyABKAIEaiACOgAAIw4gADYCACAAQQEQOyMOQQRqJA4jDkEEaiQOCx8AIw5BBGskDhAzIw4gADYCACAAIAEQPCMOQQRqJA4LPwAjDkEEayQOEDMjDiAANgIAIw5BBGskDhAzIw5BADYCACMOIAA2AgAgACABRUUQPCMOQQRqJA4jDkEEaiQOC64BAQJ/Iw5BBGskDhAzIw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QMyMOQQA2AgAjDiAANgIAIABBAhA4Iw4gACgCFCIDNgIAIAAoAggiBEEfdiADKAIIIARBAmpIcgRAQZANQYAQQfQAQQcQAAALIAQgAygCBGogAgR/IAEFIAEQJQs7AQAjDiAANgIAIABBAhA7Iw5BBGokDiMOQQRqJA4LrgEBAn8jDkEEayQOEDMjDiAANgIAAkACQAJAIwpBAWsOAgECAAsAC0EAIQILIw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEECEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEECakhyBEBBkA1BgBBBhwFBBxAAAAsgBCADKAIEaiACBH8gAQUgARAmCzsBACMOIAA2AgAgAEECEDsjDkEEaiQOIw5BBGokDguuAQECfyMOQQRrJA4QMyMOIAA2AgACQAJAAkAjCkEBaw4CAQIACwALQQAhAgsjDkEEayQOEDMjDkEANgIAIw4gADYCACAAQQQQOCMOIAAoAhQiAzYCACAAKAIIIgRBH3YgAygCCCAEQQRqSHIEQEGQDUGAEEH7AEEHEAAACyAEIAMoAgRqIAIEfyABBSABECcLNgIAIw4gADYCACAAQQQQOyMOQQRqJA4jDkEEaiQOC64BAQJ/Iw5BBGskDhAzIw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QMyMOQQA2AgAjDiAANgIAIABBBBA4Iw4gACgCFCIDNgIAIAAoAggiBEEfdiADKAIIIARBBGpIcgRAQZANQYAQQY4BQQcQAAALIAQgAygCBGogAgR/IAEFIAEQJws2AgAjDiAANgIAIABBBBA7Iw5BBGokDiMOQQRqJA4LrgEBAn8jDkEEayQOEDMjDiAANgIAAkACQAJAIwpBAWsOAgECAAsAC0EAIQILIw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEEIEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEIakhyBEBBkA1BgBBBpwFBBxAAAAsgBCADKAIEaiACBH4gAQUgARAoCzcDACMOIAA2AgAgAEEIEDsjDkEEaiQOIw5BBGokDguuAQECfyMOQQRrJA4QMyMOIAA2AgACQAJAAkAjCkEBaw4CAQIACwALQQAhAgsjDkEEayQOEDMjDkEANgIAIw4gADYCACAAQQgQOCMOIAAoAhQiAzYCACAAKAIIIgRBH3YgAygCCCAEQQhqSHIEQEGQDUGAEEGuAUEHEAAACyAEIAMoAgRqIAIEfiABBSABECgLNwMAIw4gADYCACAAQQgQOyMOQQRqJA4jDkEEaiQOC7oBAQJ/Iw5BBGskDhAzIw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QMyMOQQA2AgAjDiAANgIAIABBBBA4Iw4gACgCFCIDNgIAIAAoAggiBEEfdiADKAIIIARBBGpIcgRAQZANQYAQQd8AQQcQAAALIAIEQCAEIAMoAgRqIAE4AgAFIAQgAygCBGogAbwQJzYCAAsjDiAANgIAIABBBBA7Iw5BBGokDiMOQQRqJA4LugEBAn8jDkEEayQOEDMjDiAANgIAAkACQAJAIwpBAWsOAgECAAsAC0EAIQILIw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEEIEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEIakhyBEBBkA1BgBBB5wBBBxAAAAsgAgRAIAQgAygCBGogATkDAAUgBCADKAIEaiABvRAoNwMACyMOIAA2AgAgAEEIEDsjDkEEaiQOIw5BBGokDgsqACMOQQhrJA4QMyMOIAA2AgAjDiABNgIEIAAgASACIAMQQyMOQQhqJA4LZwAjDkEMayQOEDMjDiAANgIAIw4gATYCBCMOIAI2AggjDkEEayQOEDMjDkEANgIAAkACQAJAIwpBAWsOAgECAAsAC0HgOyECIw5B4Ds2AgALIAAgASACEEQjDkEEaiQOIw5BDGokDguEAQECfyMOQQRrJA4QMyMOIAA2AgAjDkEEayQOEDMjDkEANgIAIw4gADYCACAAQQEQJCMOIAAoAhQiATYCACAAKAIIIgIgASgCCE8EQEGQDUGAEEEzQTIQAAALIAIgASgCBGosAAAhASMOIAA2AgAgAEEBEDsjDkEEaiQOIw5BBGokDiABCyEAIw5BBGskDhAzIw4gADYCACAAEEUhACMOQQRqJA4gAAtCACMOQQRrJA4QMyMOIAA2AgAjDkEEayQOEDMjDkEANgIAIw4gADYCACAAEEVBAEchACMOQQRqJA4jDkEEaiQOIAALtAEBAn8jDkEEayQOEDMjDiAANgIAAkACQAJAIwoOAgECAAsAC0EAIQELIw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEECECQjDiAAKAIUIgI2AgAgACgCCCIDQR92IAIoAgggA0ECakhyBEBBkA1BgBBBOkEHEAAACyADIAIoAgRqLgEAIQIgAUUEQCACECUhAgsjDiAANgIAIABBAhA7Iw5BBGokDiMOQQRqJA4gAkEQdEEQdQu0AQECfyMOQQRrJA4QMyMOIAA2AgACQAJAAkAjCg4CAQIACwALQQAhAQsjDkEEayQOEDMjDkEANgIAIw4gADYCACAAQQIQJCMOIAAoAhQiAjYCACAAKAIIIgNBH3YgAigCCCADQQJqSHIEQEGQDUGAEEHPAEEHEAAACyADIAIoAgRqLwEAIQIgAUUEQCACECYhAgsjDiAANgIAIABBAhA7Iw5BBGokDiMOQQRqJA4gAkH//wNxC68BAQJ/Iw5BBGskDhAzIw4gADYCAAJAAkACQCMKDgIBAgALAAtBACEBCyMOQQRrJA4QMyMOQQA2AgAjDiAANgIAIABBBBAkIw4gACgCFCICNgIAIAAoAggiA0EfdiACKAIIIANBBGpIcgRAQZANQYAQQcIAQQcQAAALIAMgAigCBGooAgAhAiABRQRAIAIQJyECCyMOIAA2AgAgAEEEEDsjDkEEaiQOIw5BBGokDiACC68BAQJ/Iw5BBGskDhAzIw4gADYCAAJAAkACQCMKDgIBAgALAAtBACEBCyMOQQRrJA4QMyMOQQA2AgAjDiAANgIAIABBBBAkIw4gACgCFCICNgIAIAAoAggiA0EfdiACKAIIIANBBGpIcgRAQZANQYAQQdcAQQcQAAALIAMgAigCBGooAgAhAiABRQRAIAIQJyECCyMOIAA2AgAgAEEEEDsjDkEEaiQOIw5BBGokDiACC7UBAgJ/AX4jDkEEayQOEDMjDiAANgIAAkACQAJAIwoOAgECAAsAC0EAIQELIAEhAiMOQQRrJA4QMyMOQQA2AgAjDiAANgIAIABBCBAkIw4gACgCFCIBNgIAIAAoAggiA0EfdiABKAIIIANBCGpIcgRAQZANQYAQQZcBQQcQAAALIAMgASgCBGopAwAhBCACRQRAIAQQKCEECyMOIAA2AgAgAEEIEDsjDkEEaiQOIw5BBGokDiAEC7UBAgJ/AX4jDkEEayQOEDMjDiAANgIAAkACQAJAIwoOAgECAAsAC0EAIQELIAEhAiMOQQRrJA4QMyMOQQA2AgAjDiAANgIAIABBCBAkIw4gACgCFCIBNgIAIAAoAggiA0EfdiABKAIIIANBCGpIcgRAQZANQYAQQZ8BQQcQAAALIAMgASgCBGopAwAhBCACRQRAIAQQKCEECyMOIAA2AgAgAEEIEDsjDkEEaiQOIw5BBGokDiAEC7gBAgJ/AX0jDkEEayQOEDMjDiAANgIAAkACQAJAIwoOAgECAAsAC0EAIQELIw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEEEECQjDiAAKAIUIgI2AgAgACgCCCIDQR92IAIoAgggA0EEakhyBEBBkA1BgBBBI0EHEAAACyABBH0gAyACKAIEaioCAAUgAyACKAIEaigCABAnvgshBCMOIAA2AgAgAEEEEDsjDkEEaiQOIw5BBGokDiAEC7gBAgJ/AXwjDkEEayQOEDMjDiAANgIAAkACQAJAIwoOAgECAAsAC0EAIQELIw5BBGskDhAzIw5BADYCACMOIAA2AgAgAEEIECQjDiAAKAIUIgI2AgAgACgCCCIDQR92IAIoAgggA0EIakhyBEBBkA1BgBBBLEEHEAAACyABBHwgAyACKAIEaisDAAUgAyACKAIEaikDABAovwshBCMOIAA2AgAgAEEIEDsjDkEEaiQOIw5BBGokDiAECyMAIw5BBGskDhAzIw4gADYCACAAIAEQRiEAIw5BBGokDiAAC6ABACMOQQhrJA4QMyMOIAA2AgAjDiACNgIEIw5BBGskDhAzIw5BADYCAAJAAkACQCMKQQFrDgIBAgALAAtB4DshAiMOQeA7NgIACyMOQQxrJA4QMyMOQgA3AwAjDkEANgIIIw4gADYCCCAAIAEQRigCACEAIw4gADYCACMOIAI2AgQgACACEEchACMOQQxqJA4jDkEEaiQOIw5BCGokDiAACyEAIw5BBGskDhAzIw4gADYCACAAEEghACMOQQRqJA4gAAtkAQF/Iw5BBGskDhAzIw4gADYCACMOQQRrJA4QMyMOQQA2AgAgAEEAEAIgAEEAEAEgACAAKAIMEDUQICMOIAAoAhAoAgAiATYCAEEBJAogACABEDYQIiMOQQRqJA4jDkEEaiQOCwuNLVsAQYwICwE8AEGYCAsxAQAAACoAAABJAG4AdgBhAGwAaQBkACAAYgB1AGYAZgBlAHIAIABsAGUAbgBnAHQAaABBzAgLATwAQdgICzEBAAAAKgAAAEkAbgB2AGEAbABpAGQAIABiAHUAZgBmAGUAcgAgAG8AZgBmAHMAZQB0AEGMCQsBbABBmAkLVwEAAABQAAAAUgBlAGEAZAAgAGkAcwAgAG8AdQB0AHMAaQBkAGUAIAB0AGgAZQAgAGIAbwB1AG4AZABzACAAbwBmACAAdABoAGUAIABCAHUAZgBmAGUAcgBB/AkLAWwAQYgKC1sBAAAAVAAAAE8AZgBmAHMAZQB0ACAAaQBzACAAbwB1AHQAcwBpAGQAZQAgAHQAaABlACAAYgBvAHUAbgBkAHMAIABvAGYAIAB0AGgAZQAgAEIAdQBmAGYAZQByAEHsCgsBHABBjAsLASwAQZgLCw4DAAAAEAAAAIAFAACABQBBvAsLATwAQcgLCy8BAAAAKAAAAEEAbABsAG8AYwBhAHQAaQBvAG4AIAB0AG8AbwAgAGwAYQByAGcAZQBB/AsLATwAQYgMCycBAAAAIAAAAH4AbABpAGIALwByAHQALwBpAHQAYwBtAHMALgB0AHMAQfwMCwE8AEGIDQsrAQAAACQAAABJAG4AZABlAHgAIABvAHUAdAAgAG8AZgAgAHIAYQBuAGcAZQBBvA0LASwAQcgNCxsBAAAAFAAAAH4AbABpAGIALwByAHQALgB0AHMAQYwOCwE8AEGYDgslAQAAAB4AAAB+AGwAaQBiAC8AcgB0AC8AdABsAHMAZgAuAHQAcwBBzA4LASwAQdgOCyEBAAAAGgAAAH4AbABpAGIALwBhAHIAcgBhAHkALgB0AHMAQfwOCwEsAEGIDwsjAQAAABwAAABJAG4AdgBhAGwAaQBkACAAbABlAG4AZwB0AGgAQawPCwE8AEG4DwstAQAAACYAAAB+AGwAaQBiAC8AYQByAHIAYQB5AGIAdQBmAGYAZQByAC4AdABzAEHsDwsBPABB+A8LJwEAAAAgAAAAfgBsAGkAYgAvAGQAYQB0AGEAdgBpAGUAdwAuAHQAcwBBrBALATwAQbgQCykBAAAAIgAAAGEAcwBzAGUAbQBiAGwAeQAvAGkAbgBkAGUAeAAuAHQAcwBB7BALATwAQfgQCysBAAAAJAAAAH4AbABpAGIALwB0AHkAcABlAGQAYQByAHIAYQB5AC4AdABzAEGsEQsCTAMAQbgRC7YGCAAAADADAADfAFMAUwAAAEkBvAJOAAAA8AFKAAwDAACQA5kDCAMBA7ADpQMIAwEDhwU1BVIFAACWHkgAMQMAAJceVAAIAwAAmB5XAAoDAACZHlkACgMAAJoeQQC+AgAAUB+lAxMDAABSH6UDEwMAA1QfpQMTAwEDVh+lAxMDQgOAHwgfmQMAAIEfCR+ZAwAAgh8KH5kDAACDHwsfmQMAAIQfDB+ZAwAAhR8NH5kDAACGHw4fmQMAAIcfDx+ZAwAAiB8IH5kDAACJHwkfmQMAAIofCh+ZAwAAix8LH5kDAACMHwwfmQMAAI0fDR+ZAwAAjh8OH5kDAACPHw8fmQMAAJAfKB+ZAwAAkR8pH5kDAACSHyofmQMAAJMfKx+ZAwAAlB8sH5kDAACVHy0fmQMAAJYfLh+ZAwAAlx8vH5kDAACYHygfmQMAAJkfKR+ZAwAAmh8qH5kDAACbHysfmQMAAJwfLB+ZAwAAnR8tH5kDAACeHy4fmQMAAJ8fLx+ZAwAAoB9oH5kDAAChH2kfmQMAAKIfah+ZAwAAox9rH5kDAACkH2wfmQMAAKUfbR+ZAwAAph9uH5kDAACnH28fmQMAAKgfaB+ZAwAAqR9pH5kDAACqH2ofmQMAAKsfax+ZAwAArB9sH5kDAACtH20fmQMAAK4fbh+ZAwAArx9vH5kDAACyH7ofmQMAALMfkQOZAwAAtB+GA5kDAAC2H5EDQgMAALcfkQNCA5kDvB+RA5kDAADCH8ofmQMAAMMflwOZAwAAxB+JA5kDAADGH5cDQgMAAMcflwNCA5kDzB+XA5kDAADSH5kDCAMAA9MfmQMIAwED1h+ZA0IDAADXH5kDCANCA+IfpQMIAwAD4x+lAwgDAQPkH6EDEwMAAOYfpQNCAwAA5x+lAwgDQgPyH/ofmQMAAPMfqQOZAwAA9B+PA5kDAAD2H6kDQgMAAPcfqQNCA5kD/B+pA5kDAAAA+0YARgAAAAH7RgBJAAAAAvtGAEwAAAAD+0YARgBJAAT7RgBGAEwABftTAFQAAAAG+1MAVAAAABP7RAVGBQAAFPtEBTUFAAAV+0QFOwUAABb7TgVGBQAAF/tEBT0FAEH8FwuABAcICQoLDAYGBgYGBgYGBgYNBgYOBgYGBgYGBgYPEBESBhMGBgYGBgYGBgYGFBUGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYWFwYGBhgGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBhkGBgYGGgYGBgYGBgYbBgYGBgYGBgYGBgYcBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBh0GBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBh4GBgYGBgYGBgYGBgYGBgYGBgYGBgYGAEHrHAsUJCsrKysrKysrAQBUVlZWVlZWVlYAQZIdC58DGAAAACsrKysrKysHKytbVlZWVlZWVkpWVgUxUDFQMVAxUDFQMVAxUDFQJFB5MVAxUDE4UDFQMVAxUDFQMVAxUDFQTjECTg0NTgNOACRuAE4xJm5RTiRQTjkUgRsdHVMxUDFQDTFQMVAxUBtTJFAxAlx7XHtce1x7XHsUeVx7XHtcLStJA0gDeFx7FACWCgErKAYGACoGKiorB7u1Kx4AKwcrKysBKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysBKysrKysrKysrKysrKysrKysrKysrKysqKysrKysrKysrKysrK81GzSsAJSsHAQYBVVZWVlZWVVZWAiSBgYGBgRWBgYEAACsAstGy0bLRstEAAM3MAQDX19fX14OBgYGBgYGBgYGBrKysrKysrKysrBwAAAAAADFQMVAxUDFQMVAxAgAAMVAxUDFQMVAxUDFQMVAxUDFQTjFQMVBOMVAxUDFQMVAxUDFQMVAxAoemh6aHpoemh6aHpoemh6YqKysrKysrKysrKysrAAAAVFZWVlZWVlZWVlZWVgBBjyELIVRWVlZWVlZWVlZWVlYMAAwqKysrKysrKysrKysrKwcqAQBB5SELdyorKysrKysrKysrKysrKysrKysrKysrKysrK1ZWbIEVACsrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKwdsA0ErK1ZWVlZWVlZWVlZWVlZWLFYrKysrKysrKysrKysrKysrKysrKysBAEGEIwsIDGwAAAAAAAYAQbIjC+gCBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiVWep4mBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBgErK09WViwrf1ZWOSsrVVZWKytPVlYsK39WVoE3dVt7XCsrT1ZWAqwEAAA5KytVVlYrK09WViwrK1ZWMhOBVwBvgX7J134tgYEOfjl/b1cAgYF+FQB+AysrKysrKysrKysrKwcrJCuXKysrKysrKysrKisrKysrVlZWVlaAgYGBgTm7KisrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysBgYGBgYGBgYGBgYGBgYGByaysrKysrKysrKysrKysrNANAE4xArTBwdfXJFAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUNfXU8FH1NfX1wUrKysrKysrKysrKysHAQABAEH1JgsfTjFQMVAxUDFQMVAxUDFQDQAAAAAAJFAxUDFQMVAxUABBticLVisrKysrKysrKysreVx7XHtPe1x7XHtce1x7XHtce1x7XHtce1wtKyt5FFx7XC15KlwnXHtce1x7pAAKtFx7XHtPA3g4KysrKysrKysrKysrK08tKysBAEGnKAsBSABBsSgLGyorKysrKysrKysrKysrKysrKysrKysrKysrKwBB7SgLFCsrKysrKysrBwBIVlZWVlZWVlYCAEG4KQsbKysrKysrKysrKysrK1VWVlZWVlZWVlZWVlYOAEHyKQsaJCsrKysrKysrKysrBwBWVlZWVlZWVlZWVlYAQbgqCyckKysrKysrKysrKysrKysrKwcAAAAAVlZWVlZWVlZWVlZWVlZWVlYAQZkrCxYqKysrKysrKysrK1ZWVlZWVlZWVlYOAEHPKwsWKisrKysrKysrKytWVlZWVlZWVlZWDgBBkCwLFysrKysrKysrKysrVVZWVlZWVlZWVlYOAEHpLAsICAAAVgEAADkAQfgsC7wHASAAAADg//8Avx0AAOcCAAB5AAACJAAAAQEAAAD///8AAAAAAQIAAAD+//8BOf//ABj//wGH//8A1P7/AMMAAAHSAAABzgAAAc0AAAFPAAABygAAAcsAAAHPAAAAYQAAAdMAAAHRAAAAowAAAdUAAACCAAAB1gAAAdoAAAHZAAAB2wAAADgAAAMAAAAAsf//AZ///wHI//8CKCQAAAAAAAEBAAAA////ADP//wAm//8Bfv//ASsqAAFd//8BKCoAAD8qAAE9//8BRQAAAUcAAAAfKgAAHCoAAB4qAAAu//8AMv//ADb//wA1//8AT6UAAEulAAAx//8AKKUAAESlAAAv//8ALf//APcpAABBpQAA/SkAACv//wAq//8A5ykAAEOlAAAqpQAAu///ACf//wC5//8AJf//ABWlAAASpQACJEwAAAAAAAEgAAAA4P//AQEAAAD///8AVAAAAXQAAAEmAAABJQAAAUAAAAE/AAAA2v//ANv//wDh//8AwP//AMH//wEIAAAAwv//AMf//wDR//8Ayv//APj//wCq//8AsP//AAcAAACM//8BxP//AKD//wH5//8CGnAAAQEAAAD///8BIAAAAOD//wFQAAABDwAAAPH//wAAAAABMAAAAND//wEBAAAA////AAAAAADACwABYBwAAAAAAAHQlwABCAAAAPj//wIFigAAAAAAAUD0/wCe5/8AwokAANvn/wCS5/8Ak+f/AJzn/wCd5/8ApOf/AAAAAAA4igAABIoAAOYOAAEBAAAA////AAAAAADF//8BQeL/Ah2PAAAIAAAB+P//AAAAAABWAAABqv//AEoAAABkAAAAgAAAAHAAAAB+AAAACQAAAbb//wH3//8A2+P/AZz//wGQ//8BgP//AYL//wIFrAAAAAAAARAAAADw//8BHAAAAQEAAAGj4v8BQd//Abrf/wDk//8CC7EAAQEAAAD///8BMAAAAND//wAAAAABCdb/ARrx/wEZ1v8A1dX/ANjV/wHk1f8BA9b/AeHV/wHi1f8BwdX/AAAAAACg4/8AAAAAAQEAAAD///8CDLwAAAAAAAEBAAAA////Abxa/wGgAwAB/HX/Adha/wAwAAABsVr/AbVa/wG/Wv8B7lr/AdZa/wHrWv8B0P//Ab1a/wHIdf8AAAAAADBo/wBg/P8AAAAAASAAAADg//8AAAAAASgAAADY//8AAAAAAUAAAADA//8AAAAAASAAAADg//8AAAAAASAAAADg//8AAAAAASIAAADe//8AQbU0CwUGJ1FvdwBBxDQLEnwAAH8AAAAAAAAAAIOOkpcAqgBB4DQLArTEAEHaNQsGxskAAADbAEGzNgsO3gAAAADhAAAAAAAAAOQAQcw2CwHnAEGiNwsB6gBBnTgLAe0AQbQ4C5ADMAwxDXgOfw+AEIERhhKJE4oTjhSPFZAWkxOUF5UYlhmXGpobnBmdHJ4dnx6mH6kfrh+xILIgtyG/IsUjyCPLI90k8iP2JfcmIC06Lj0vPjA/MUAxQzJEM0U0UDVRNlI3UzhUOVk6WztcPGE9Yz5lP2ZAaEFpQmpAa0NsRG9CcUVyRnVHfUiCSYdKiUuKTItMjE2STp1PnlBFV3sdfB19HX9YhlmIWolailqMW45cj1ysXa1erl6vXsJfzGDNYc5hz2LQY9Fk1WXWZtdn8GjxafJq82v0bPVt+W79Lf4t/y1QaVFpUmlTaVRpVWlWaVdpWGlZaVppW2lcaV1pXmlfaYIAgwCEAIUAhgCHAIgAiQDAdc92gImBioKLhYyGjXCdcZ12nneeeJ95n3qge6B8oX2hs6K6o7ujvKS+pcOizKTaptum5Wrqp+un7G7zovio+aj6qfup/KQmsCqxK7JOs4QIYrpju2S8Zb1mvm2/bsBvwXDCfsN/w33PjdCU0avSrNOt1LDVsday18TYxdnG2gBBzDsLARwAQdg7Cw8BAAAACAAAAFUAVABGADgAQew7CwEcAEH4OwsRAQAAAAoAAABVAFQARgAtADgAQYw8CwEcAEGYPAsRAQAAAAoAAABVAFQARgAxADYAQaw8CwEcAEG4PAsTAQAAAAwAAABVAFQARgAtADEANgBBzDwLATwAQdg8CzEBAAAAKgAAAFUAbgBzAHUAcABwAG8AcgB0AGUAZAAgAGUAbgBjAG8AZABpAG4AZwAgAEGMPQsBHABBmD0LDwEAAAAIAAAAbgB1AGwAbABBrD0LARwAQbg9CwEBAEHMPQsBPABB2D0LKQEAAAAiAAAAYQBzAHMAZQBtAGIAbAB5AC8AdQB0AGkAbABzAC4AdABzAEGMPgsBLABBmD4LIwEAAAAcAAAAfgBsAGkAYgAvAHMAdAByAGkAbgBnAC4AdABzAEG8PgsBfABByD4LZQEAAABeAAAARQBsAGUAbQBlAG4AdAAgAHQAeQBwAGUAIABtAHUAcwB0ACAAYgBlACAAbgB1AGwAbABhAGIAbABlACAAaQBmACAAYQByAHIAYQB5ACAAaQBzACAAaABvAGwAZQB5AEG8PwsBPABByD8LMQEAAAAqAAAATwBiAGoAZQBjAHQAIABhAGwAcgBlAGEAZAB5ACAAcABpAG4AbgBlAGQAQfw/CwE8AEGIwAALLwEAAAAoAAAATwBiAGoAZQBjAHQAIABpAHMAIABuAG8AdAAgAHAAaQBuAG4AZQBkAEHAwAALDQkAAAAgAAAAAAAAACAAQdzAAAsNAkEAAAAAAABBAAAAAgBB/MAACwlBAAAAAgAAAKQ=";

    // Runtime header offsets
    const ID_OFFSET = -8;
    const SIZE_OFFSET = -4;

    // Runtime ids
    const ARRAYBUFFER_ID = 0;
    const STRING_ID = 1;
    // const ARRAYBUFFERVIEW_ID = 2;

    // Runtime type information
    const ARRAYBUFFERVIEW = 1 << 0;
    const ARRAY = 1 << 1;
    const STATICARRAY = 1 << 2;
    // const SET = 1 << 3;
    // const MAP = 1 << 4;
    const VAL_ALIGN_OFFSET = 6;
    // const VAL_ALIGN = 1 << VAL_ALIGN_OFFSET;
    const VAL_SIGNED = 1 << 11;
    const VAL_FLOAT = 1 << 12;
    // const VAL_NULLABLE = 1 << 13;
    const VAL_MANAGED = 1 << 14;
    // const KEY_ALIGN_OFFSET = 15;
    // const KEY_ALIGN = 1 << KEY_ALIGN_OFFSET;
    // const KEY_SIGNED = 1 << 20;
    // const KEY_FLOAT = 1 << 21;
    // const KEY_NULLABLE = 1 << 22;
    // const KEY_MANAGED = 1 << 23;

    // Array(BufferView) layout
    const ARRAYBUFFERVIEW_BUFFER_OFFSET = 0;
    const ARRAYBUFFERVIEW_DATASTART_OFFSET = 4;
    const ARRAYBUFFERVIEW_DATALENGTH_OFFSET = 8;
    const ARRAYBUFFERVIEW_SIZE = 12;
    const ARRAY_LENGTH_OFFSET = 12;
    const ARRAY_SIZE = 16;

    const BIGINT = typeof BigUint64Array !== "undefined";
    const THIS = Symbol();

    const STRING_DECODE_THRESHOLD = 32;
    const decoder = new TextDecoder("utf-16le");

    /** Gets a string from an U32 and an U16 view on a memory. */
    function getStringImpl(buffer, ptr) {
      const len = new Uint32Array(buffer)[ptr + SIZE_OFFSET >>> 2] >>> 1;
      const arr = new Uint16Array(buffer, ptr, len);
      if (len <= STRING_DECODE_THRESHOLD) {
        return String.fromCharCode.apply(String, arr);
      }
      return decoder.decode(arr);
    }

    /** Prepares the base module prior to instantiation. */
    function preInstantiate(imports) {
      const extendedExports = {};

      function getString(memory, ptr) {
        if (!memory) return "<yet unknown>";
        return getStringImpl(memory.buffer, ptr);
      }

      // add common imports used by stdlib for convenience
      const env = (imports.env = imports.env || {});
      env.abort = env.abort || function abort(msg, file, line, colm) {
        const memory = extendedExports.memory || env.memory; // prefer exported, otherwise try imported
        throw Error(`abort: ${getString(memory, msg)} at ${getString(memory, file)}:${line}:${colm}`);
      };
      env.trace = env.trace || function trace(msg, n, ...args) {
        const memory = extendedExports.memory || env.memory;
        console.log(`trace: ${getString(memory, msg)}${n ? " " : ""}${args.slice(0, n).join(", ")}`);
      };
      env.seed = env.seed || Date.now;
      imports.Math = imports.Math || Math;
      imports.Date = imports.Date || Date;

      return extendedExports;
    }

    const E_NOEXPORTRUNTIME = "Operation requires compiling with --exportRuntime";
    const F_NOEXPORTRUNTIME = function() { throw Error(E_NOEXPORTRUNTIME); };

    /** Prepares the final module once instantiation is complete. */
    function postInstantiate(extendedExports, instance) {
      const exports = instance.exports;
      const memory = exports.memory;
      const table = exports.table;
      const __new = exports.__new || F_NOEXPORTRUNTIME;
      const __pin = exports.__pin || F_NOEXPORTRUNTIME;
      const __unpin = exports.__unpin || F_NOEXPORTRUNTIME;
      const __collect = exports.__collect || F_NOEXPORTRUNTIME;
      const __rtti_base = exports.__rtti_base || ~0; // oob if not present

      extendedExports.__new = __new;
      extendedExports.__pin = __pin;
      extendedExports.__unpin = __unpin;
      extendedExports.__collect = __collect;

      /** Gets the runtime type info for the given id. */
      function getInfo(id) {
        const U32 = new Uint32Array(memory.buffer);
        const count = U32[__rtti_base >>> 2];
        if ((id >>>= 0) >= count) throw Error(`invalid id: ${id}`);
        return U32[(__rtti_base + 4 >>> 2) + id * 2];
      }

      /** Gets and validate runtime type info for the given id for array like objects */
      function getArrayInfo(id) {
        const info = getInfo(id);
        if (!(info & (ARRAYBUFFERVIEW | ARRAY | STATICARRAY))) throw Error(`not an array: ${id}, flags=${info}`);
        return info;
      }

      /** Gets the runtime base id for the given id. */
      function getBase(id) {
        const U32 = new Uint32Array(memory.buffer);
        const count = U32[__rtti_base >>> 2];
        if ((id >>>= 0) >= count) throw Error(`invalid id: ${id}`);
        return U32[(__rtti_base + 4 >>> 2) + id * 2 + 1];
      }

      /** Gets the runtime alignment of a collection's values. */
      function getValueAlign(info) {
        return 31 - Math.clz32((info >>> VAL_ALIGN_OFFSET) & 31); // -1 if none
      }

      /** Gets the runtime alignment of a collection's keys. */
      // function getKeyAlign(info) {
      //   return 31 - Math.clz32((info >>> KEY_ALIGN_OFFSET) & 31); // -1 if none
      // }

      /** Allocates a new string in the module's memory and returns its pointer. */
      function __newString(str) {
        if (str == null) return 0;
        const length = str.length;
        const ptr = __new(length << 1, STRING_ID);
        const U16 = new Uint16Array(memory.buffer);
        for (var i = 0, p = ptr >>> 1; i < length; ++i) U16[p + i] = str.charCodeAt(i);
        return ptr;
      }

      extendedExports.__newString = __newString;

      /** Reads a string from the module's memory by its pointer. */
      function __getString(ptr) {
        if (!ptr) return null;
        const buffer = memory.buffer;
        const id = new Uint32Array(buffer)[ptr + ID_OFFSET >>> 2];
        if (id !== STRING_ID) throw Error(`not a string: ${ptr}`);
        return getStringImpl(buffer, ptr);
      }

      extendedExports.__getString = __getString;

      /** Gets the view matching the specified alignment, signedness and floatness. */
      function getView(alignLog2, signed, float) {
        const buffer = memory.buffer;
        if (float) {
          switch (alignLog2) {
            case 2: return new Float32Array(buffer);
            case 3: return new Float64Array(buffer);
          }
        } else {
          switch (alignLog2) {
            case 0: return new (signed ? Int8Array : Uint8Array)(buffer);
            case 1: return new (signed ? Int16Array : Uint16Array)(buffer);
            case 2: return new (signed ? Int32Array : Uint32Array)(buffer);
            case 3: return new (signed ? BigInt64Array : BigUint64Array)(buffer);
          }
        }
        throw Error(`unsupported align: ${alignLog2}`);
      }

      /** Allocates a new array in the module's memory and returns its pointer. */
      function __newArray(id, values) {
        const info = getArrayInfo(id);
        const align = getValueAlign(info);
        const length = values.length;
        const buf = __new(length << align, info & STATICARRAY ? id : ARRAYBUFFER_ID);
        let result;
        if (info & STATICARRAY) {
          result = buf;
        } else {
          const arr = __new(info & ARRAY ? ARRAY_SIZE : ARRAYBUFFERVIEW_SIZE, id);
          const U32 = new Uint32Array(memory.buffer);
          U32[arr + ARRAYBUFFERVIEW_BUFFER_OFFSET >>> 2] = buf;
          U32[arr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2] = buf;
          U32[arr + ARRAYBUFFERVIEW_DATALENGTH_OFFSET >>> 2] = length << align;
          if (info & ARRAY) U32[arr + ARRAY_LENGTH_OFFSET >>> 2] = length;
          result = arr;
        }
        const view = getView(align, info & VAL_SIGNED, info & VAL_FLOAT);
        if (info & VAL_MANAGED) {
          for (let i = 0; i < length; ++i) {
            const value = values[i];
            view[(buf >>> align) + i] = value;
          }
        } else {
          view.set(values, buf >>> align);
        }
        return result;
      }

      extendedExports.__newArray = __newArray;

      /** Gets a live view on an array's values in the module's memory. Infers the array type from RTTI. */
      function __getArrayView(arr) {
        const U32 = new Uint32Array(memory.buffer);
        const id = U32[arr + ID_OFFSET >>> 2];
        const info = getArrayInfo(id);
        const align = getValueAlign(info);
        let buf = info & STATICARRAY
          ? arr
          : U32[arr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2];
        const length = info & ARRAY
          ? U32[arr + ARRAY_LENGTH_OFFSET >>> 2]
          : U32[buf + SIZE_OFFSET >>> 2] >>> align;
        return getView(align, info & VAL_SIGNED, info & VAL_FLOAT).subarray(buf >>>= align, buf + length);
      }

      extendedExports.__getArrayView = __getArrayView;

      /** Copies an array's values from the module's memory. Infers the array type from RTTI. */
      function __getArray(arr) {
        const input = __getArrayView(arr);
        const len = input.length;
        const out = new Array(len);
        for (let i = 0; i < len; i++) out[i] = input[i];
        return out;
      }

      extendedExports.__getArray = __getArray;

      /** Copies an ArrayBuffer's value from the module's memory. */
      function __getArrayBuffer(ptr) {
        const buffer = memory.buffer;
        const length = new Uint32Array(buffer)[ptr + SIZE_OFFSET >>> 2];
        return buffer.slice(ptr, ptr + length);
      }

      extendedExports.__getArrayBuffer = __getArrayBuffer;

      /** Copies a typed array's values from the module's memory. */
      function getTypedArray(Type, alignLog2, ptr) {
        return new Type(getTypedArrayView(Type, alignLog2, ptr));
      }

      /** Gets a live view on a typed array's values in the module's memory. */
      function getTypedArrayView(Type, alignLog2, ptr) {
        const buffer = memory.buffer;
        const U32 = new Uint32Array(buffer);
        const bufPtr = U32[ptr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2];
        return new Type(buffer, bufPtr, U32[bufPtr + SIZE_OFFSET >>> 2] >>> alignLog2);
      }

      /** Attach a set of get TypedArray and View functions to the exports. */
      function attachTypedArrayFunctions(ctor, name, align) {
        extendedExports[`__get${name}`] = getTypedArray.bind(null, ctor, align);
        extendedExports[`__get${name}View`] = getTypedArrayView.bind(null, ctor, align);
      }

      [
        Int8Array,
        Uint8Array,
        Uint8ClampedArray,
        Int16Array,
        Uint16Array,
        Int32Array,
        Uint32Array,
        Float32Array,
        Float64Array
      ].forEach(ctor => {
        attachTypedArrayFunctions(ctor, ctor.name, 31 - Math.clz32(ctor.BYTES_PER_ELEMENT));
      });

      if (BIGINT) {
        [BigUint64Array, BigInt64Array].forEach(ctor => {
          attachTypedArrayFunctions(ctor, ctor.name.slice(3), 3);
        });
      }

      /** Tests whether an object is an instance of the class represented by the specified base id. */
      function __instanceof(ptr, baseId) {
        const U32 = new Uint32Array(memory.buffer);
        let id = U32[ptr + ID_OFFSET >>> 2];
        if (id <= U32[__rtti_base >>> 2]) {
          do {
            if (id == baseId) return true;
            id = getBase(id);
          } while (id);
        }
        return false;
      }

      extendedExports.__instanceof = __instanceof;

      // Pull basic exports to extendedExports so code in preInstantiate can use them
      extendedExports.memory = extendedExports.memory || memory;
      extendedExports.table  = extendedExports.table  || table;

      // Demangle exports and provide the usual utility on the prototype
      return demangle(exports, extendedExports);
    }

    function isResponse(src) {
      return typeof Response !== "undefined" && src instanceof Response;
    }

    function isModule(src) {
      return src instanceof WebAssembly.Module;
    }

    /** Asynchronously instantiates an AssemblyScript module from anything that can be instantiated. */
    async function instantiate(source, imports = {}) {
      if (isResponse(source = await source)) return instantiateStreaming(source, imports);
      const module = isModule(source) ? source : await WebAssembly.compile(source);
      const extended = preInstantiate(imports);
      const instance = await WebAssembly.instantiate(module, imports);
      const exports = postInstantiate(extended, instance);
      return { module, instance, exports };
    }

    /** Asynchronously instantiates an AssemblyScript module from a response, i.e. as obtained by `fetch`. */
    async function instantiateStreaming(source, imports = {}) {
      if (!WebAssembly.instantiateStreaming) {
        return instantiate(
          isResponse(source = await source)
            ? source.arrayBuffer()
            : source,
          imports
        );
      }
      const extended = preInstantiate(imports);
      const result = await WebAssembly.instantiateStreaming(source, imports);
      const exports = postInstantiate(extended, result.instance);
      return { ...result, exports };
    }

    /** Demangles an AssemblyScript module's exports to a friendly object structure. */
    function demangle(exports, extendedExports = {}) {
      const setArgumentsLength = exports["__argumentsLength"]
        ? length => { exports["__argumentsLength"].value = length; }
        : exports["__setArgumentsLength"] || exports["__setargc"] || (() => { /* nop */ });
      for (let internalName in exports) {
        if (!Object.prototype.hasOwnProperty.call(exports, internalName)) continue;
        const elem = exports[internalName];
        let parts = internalName.split(".");
        let curr = extendedExports;
        while (parts.length > 1) {
          let part = parts.shift();
          if (!Object.prototype.hasOwnProperty.call(curr, part)) curr[part] = {};
          curr = curr[part];
        }
        let name = parts[0];
        let hash = name.indexOf("#");
        if (hash >= 0) {
          const className = name.substring(0, hash);
          const classElem = curr[className];
          if (typeof classElem === "undefined" || !classElem.prototype) {
            const ctor = function(...args) {
              return ctor.wrap(ctor.prototype.constructor(0, ...args));
            };
            ctor.prototype = {
              valueOf() { return this[THIS]; }
            };
            ctor.wrap = function(thisValue) {
              return Object.create(ctor.prototype, { [THIS]: { value: thisValue, writable: false } });
            };
            if (classElem) Object.getOwnPropertyNames(classElem).forEach(name =>
              Object.defineProperty(ctor, name, Object.getOwnPropertyDescriptor(classElem, name))
            );
            curr[className] = ctor;
          }
          name = name.substring(hash + 1);
          curr = curr[className].prototype;
          if (/^(get|set):/.test(name)) {
            if (!Object.prototype.hasOwnProperty.call(curr, name = name.substring(4))) {
              let getter = exports[internalName.replace("set:", "get:")];
              let setter = exports[internalName.replace("get:", "set:")];
              Object.defineProperty(curr, name, {
                get() { return getter(this[THIS]); },
                set(value) { setter(this[THIS], value); },
                enumerable: true
              });
            }
          } else {
            if (name === 'constructor') {
              (curr[name] = (...args) => {
                setArgumentsLength(args.length);
                return elem(...args);
              }).original = elem;
            } else { // instance method
              (curr[name] = function(...args) { // !
                setArgumentsLength(args.length);
                return elem(this[THIS], ...args);
              }).original = elem;
            }
          }
        } else {
          if (/^(get|set):/.test(name)) {
            if (!Object.prototype.hasOwnProperty.call(curr, name = name.substring(4))) {
              Object.defineProperty(curr, name, {
                get: exports[internalName.replace("set:", "get:")],
                set: exports[internalName.replace("get:", "set:")],
                enumerable: true
              });
            }
          } else if (typeof elem === "function" && elem !== setArgumentsLength) {
            (curr[name] = (...args) => {
              setArgumentsLength(args.length);
              return elem(...args);
            }).original = elem;
          } else {
            curr[name] = elem;
          }
        }
      }
      return extendedExports;
    }

    function readAssembly() {
        if (globalThis.atob) {
            var source = globalThis.atob(wasm);
            var sourceLength = source.length;
            var bytes = new Uint8Array(sourceLength);
            for (var i = 0; i < sourceLength; i++) {
                bytes[i] = source.charCodeAt(i);
            }
            return bytes.buffer;
        }
        else {
            return Buffer.from(wasm, 'base64');
        }
    }
    var buffer;
    var Buffer$1 = {
        init: function () {
            return __awaiter(this, void 0, void 0, function () {
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0:
                            if (buffer)
                                return [2 /*return*/, buffer];
                            return [4 /*yield*/, instantiate(readAssembly())];
                        case 1: return [2 /*return*/, (buffer = (_a.sent()).exports)];
                    }
                });
            });
        }
    };

    /**
     * @module examples
     */
    var raf;
    var index = 0;
    var view = document.getElementById('view');
    function onStart() {
        onStop();
        Buffer$1.init().then(function (_a) {
            var Buffer = _a.Buffer, __newString = _a.__newString, __getUint8Array = _a.__getUint8Array;
            var buffer = new Buffer();
            buffer.write(__newString(++index + ": A buffer tool using WebAssembly."));
            view.innerHTML = hex(__getUint8Array(buffer.bytes));
            raf = window.requestAnimationFrame(onStart);
        });
    }
    function onStop() {
        window.cancelAnimationFrame(raf);
    }
    document.getElementById('start').addEventListener('click', onStart, false);
    document.getElementById('stop').addEventListener('click', onStop, false);

})));
