/**
 * @module Buffer
 * @license MIT
 * @version 0.0.1
 * @author nuintun
 * @description A buffer tool using WebAssembly.
 * @see https://github.com/nuintun/AssemblyBuffer#readme
 */

(function (factory) {
    typeof define === 'function' && define.amd ? define('buffer', factory) :
    factory();
})((function () { 'use strict';

    /**
     * @module hex
     */
    /**
     * @type {string[]}
     * @description 已获得的 hex 映射表
     */
    var mapping = [];
    // 字母映射表
    var alphabet = '0123456789ABCDEF';
    // 生成映射表
    for (var i = 0; i < 16; ++i) {
        var i16 = i * 16;
        for (var j = 0; j < 16; ++j) {
            mapping[i16 + j] = alphabet[i] + alphabet[j];
        }
    }
    /**
     * @function zero
     * @description 数字左边补零操作
     * @param {number} value
     * @param {number} max
     * @returns {string}
     */
    function zero(value, max) {
        return (value > 0xff ? value.toString(16) : mapping[value]).padStart(max, '0');
    }
    /**
     * @function hex
     * @function Hex 查看器
     * @param {Uint8Array} buffer
     * @returns {string}
     */
    function hex(buffer) {
        var length = buffer.length;
        var last = length % 16 || 16;
        var rows = Math.ceil(length / 16);
        var offsetLength = Math.max(6, length.toString(16).length);
        var rowBytes;
        var index = 0;
        var rowSpaces;
        var hex = "OFFSET  ";
        for (var i = 0; i < 16; i++) {
            hex += " ".concat(zero(i, 2));
        }
        hex += "\n";
        if (length) {
            hex += "\n";
        }
        for (var i = 0; i < rows; i++) {
            hex += "".concat(zero(index, offsetLength), "  ");
            rowBytes = i === rows - 1 ? last : 16;
            rowSpaces = 16 - rowBytes;
            for (var j = 0; j < rowBytes; j++) {
                hex += " ".concat(zero(buffer[index++], 2));
            }
            for (var j = 0; j <= rowSpaces; j++) {
                hex += "   ";
            }
            index -= rowBytes;
            for (var j = 0; j < rowBytes; j++) {
                var byte = buffer[index++];
                hex += (byte > 31 && byte < 127) || byte > 159 ? String.fromCharCode(byte) : ".";
            }
            hex += "\n";
        }
        return hex.trim();
    }

    /*! *****************************************************************************
    Copyright (c) Microsoft Corporation.

    Permission to use, copy, modify, and/or distribute this software for any
    purpose with or without fee is hereby granted.

    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
    REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
    AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
    INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
    LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
    OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
    PERFORMANCE OF THIS SOFTWARE.
    ***************************************************************************** */

    function __awaiter(thisArg, _arguments, P, generator) {
        function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
        return new (P || (P = Promise))(function (resolve, reject) {
            function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
            function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
            function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
            step((generator = generator.apply(thisArg, _arguments || [])).next());
        });
    }

    function __generator(thisArg, body) {
        var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
        return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
        function verb(n) { return function (v) { return step([n, v]); }; }
        function step(op) {
            if (f) throw new TypeError("Generator is already executing.");
            while (_) try {
                if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
                if (y = 0, t) op = [op[0] & 2, t.value];
                switch (op[0]) {
                    case 0: case 1: t = op; break;
                    case 4: _.label++; return { value: op[1], done: false };
                    case 5: _.label++; y = op[1]; op = [0]; continue;
                    case 7: op = _.ops.pop(); _.trys.pop(); continue;
                    default:
                        if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                        if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                        if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                        if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                        if (t[2]) _.ops.pop();
                        _.trys.pop(); continue;
                }
                op = body.call(thisArg, _);
            } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
            if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
        }
    }

    var wasm = "AGFzbQEAAAABWRBgAn9/AGABfwF/YAJ/fwF/YAN/f38AYAF/AGAAAGADf39/AX9gBH9/f38AYAN/fn8AYAJ/fwF+YAABf2ABfgF+YAN/fX8AYAN/fH8AYAJ/fwF9YAJ/fwF8Ag0BA2VudgVhYm9ydAAHA2tqAAABAQEFAAAEAwQEAQAAAAMFCgICAAACAwIDBQAAAAEBAAADAAABAQsBAQIDAgcBBAUEBAUFBgABAAEDAQIGAQEGBgIGAQABAAEBAAAAAAAAAwMDAwgIDA0HAwEBAQICAgIJCQ4PAgYBBAUDAQABBlAPfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38BQQALfwFBAAt/AUEAC38AQQQLfwBBBQt/AEHgwAALfwFBrMEBCwfUBi8OVUlOVDhfQVJSQVlfSUQDCwZCdWZmZXIDDAVfX25ldwAYBV9fcGluADAHX191bnBpbgAxCV9fY29sbGVjdAAyC19fcnR0aV9iYXNlAw0GbWVtb3J5AgAUX19zZXRBcmd1bWVudHNMZW5ndGgANBJCdWZmZXIjY29uc3RydWN0b3IARRFCdWZmZXIjZ2V0Om9mZnNldABGEUJ1ZmZlciNzZXQ6b2Zmc2V0AEcRQnVmZmVyI2dldDpsZW5ndGgASBFCdWZmZXIjc2V0Omxlbmd0aABJEUJ1ZmZlciNnZXQ6YnVmZmVyAEoQQnVmZmVyI2dldDpieXRlcwBLDEJ1ZmZlciNhbGxvYwBMEUJ1ZmZlciNzdGVwT2Zmc2V0AE0RQnVmZmVyI2Fzc2VydFJlYWQAThBCdWZmZXIjd3JpdGVJbnQ4AE8RQnVmZmVyI3dyaXRlVWludDgAUBNCdWZmZXIjd3JpdGVCb29sZWFuAFERQnVmZmVyI3dyaXRlSW50MTYAUhJCdWZmZXIjd3JpdGVVaW50MTYAUxFCdWZmZXIjd3JpdGVJbnQzMgBUEkJ1ZmZlciN3cml0ZVVpbnQzMgBVEUJ1ZmZlciN3cml0ZUludDY0AFYSQnVmZmVyI3dyaXRlVWludDY0AFcTQnVmZmVyI3dyaXRlRmxvYXQzMgBYE0J1ZmZlciN3cml0ZUZsb2F0NjQAWRFCdWZmZXIjd3JpdGVCeXRlcwBaDEJ1ZmZlciN3cml0ZQBbD0J1ZmZlciNyZWFkSW50OABcEEJ1ZmZlciNyZWFkVWludDgAXRJCdWZmZXIjcmVhZEJvb2xlYW4AXhBCdWZmZXIjcmVhZEludDE2AF8RQnVmZmVyI3JlYWRVaW50MTYAYBBCdWZmZXIjcmVhZEludDMyAGERQnVmZmVyI3JlYWRVaW50MzIAYhBCdWZmZXIjcmVhZEludDY0AGMRQnVmZmVyI3JlYWRVaW50NjQAZBJCdWZmZXIjcmVhZEZsb2F0MzIAZRJCdWZmZXIjcmVhZEZsb2F0NjQAZhBCdWZmZXIjcmVhZEJ5dGVzAGcLQnVmZmVyI3JlYWQAaA9CdWZmZXIjdG9TdHJpbmcAaQxCdWZmZXIjY2xlYXIAaggBNQr3YGoJACAAIAE2AgQLCQAgACABNgIICxAAIAAgABABIAAgABACIAALCgAgACgCBEF8cQsKACAAKAIEQQNxC38BAn9BkA0QDEGQDxAMQfA+EAxB0AsQDEHwPxAMQbDAABAMQaA8EAxBwBEQDEGgCBAMQeAIEAxBoAkQDEGQChAMQaALEAwjBCIBEAQhAANAIAAgAUcEQCAAEAVBA0cEQEEAQZAMQZ8BQRAQAAALIABBFGoQMyAAEAQhAAwBCwsLEQAgACABIAAoAgRBfHFyEAELEQAgACAAKAIEQQNxIAFyEAELUwEBfyAAEAQiAUUEQEEAIABBrMEBSSAAKAIIG0UEQEEAQZAMQf8AQRIQAAALDwsgACgCCCIARQRAQQBBkAxBgwFBEBAAAAsgASAAEAIgACABEAgLJgEBfyABKAIIIQMgACABIAJyEAEgACADEAIgAyAAEAggASAAEAILegECfyMFIABGBEAgACgCCCIBRQRAQQBBkAxBkwFBHhAAAAsgASQFCyAAEAkjBiEBIAAoAgwiAkEBTQR/QQEFQeDAACgCACACSQRAQZANQdANQRZBHBAAAAsgAkEDdEHkwABqKAIAQSBxCyECIAAgASMHRUECIAIbEAoLIwAgAEUEQA8LIABBFGsiABAFIwdGBEAgABALIwNBAWokAwsLDQAgACgCAEF8cUEEagsJACAAIAE2AgALkQIBBH8gASgCACICQQFxRQRAQQBBoA5BjAJBDhAAAAsgAkF8cSICQQxJBEBBAEGgDkGOAkEOEAAACyACQYACSQR/IAJBBHYFQR8gAkH8////AyACQfz///8DSRsiAmdrIgRBB2shAyACIARBBGt2QRBzCyICQRBJIANBF0lxRQRAQQBBoA5BnAJBDhAAAAsgASgCCCEFIAEoAgQiBARAIAQgBRACCyAFBEAgBSAEEAELIAIgA0EEdGpBAnQgAGooAmAgAUYEQCACIANBBHRqQQJ0IABqIAU2AmAgBUUEQCADQQJ0IABqIgEoAgRBfiACd3EhAiABIAI2AgQgAkUEQCAAIAAoAgBBfiADd3EQDgsLCwu8AwEFfyABRQRAQQBBoA5ByQFBDhAAAAsgASgCACIDQQFxRQRAQQBBoA5BywFBDhAAAAsgAUEEaiABKAIAQXxxaiIEKAIAIgJBAXEEQCAAIAQQDyABIANBBGogAkF8cWoiAxAOIAFBBGogASgCAEF8cWoiBCgCACECCyADQQJxBEAgAUEEaygCACIBKAIAIgZBAXFFBEBBAEGgDkHdAUEQEAAACyAAIAEQDyABIAZBBGogA0F8cWoiAxAOCyAEIAJBAnIQDiADQXxxIgJBDEkEQEEAQaAOQekBQQ4QAAALIAIgAUEEamogBEcEQEEAQaAOQeoBQQ4QAAALIARBBGsgATYCACACQYACSQR/IAJBBHYFQR8gAkH8////AyACQfz///8DSRsiAmdrIgNBB2shBSACIANBBGt2QRBzCyICQRBJIAVBF0lxRQRAQQBBoA5B+wFBDhAAAAsgAiAFQQR0akECdCAAaigCYCEDIAFBABABIAEgAxACIAMEQCADIAEQAQsgAiAFQQR0akECdCAAaiABNgJgIAAgACgCAEEBIAV0chAOIAVBAnQgAGoiACAAKAIEQQEgAnRyNgIEC8kBAQJ/IAEgAksEQEEAQaAOQfkCQQ4QAAALIAFBE2pBcHFBBGshASAAKAKgDCIEBEAgASAEQQRqSQRAQQBBoA5BgANBEBAAAAsgBCABQRBrRgRAIAQoAgAhAyABQRBrIQELBSABIABBpAxqSQRAQQBBoA5BjQNBBRAAAAsLIAJBcHEgAWsiAkEUSQRADwsgASADQQJxIAJBCGsiAkEBcnIQDiABQQAQASABQQAQAiACIAFBBGpqIgJBAhAOIAAgAjYCoAwgACABEBALlQEBAn8/ACIBQQBMBH9BASABa0AAQQBIBUEACwRAAAtBsMEBQQAQDkHQzQFBADYCAANAIABBF0kEQCAAQQJ0QbDBAWpBADYCBEEAIQEDQCABQRBJBEAgASAAQQR0akECdEGwwQFqQQA2AmAgAUEBaiEBDAELCyAAQQFqIQAMAQsLQbDBAUHUzQE/AEEQdBARQbDBASQJC6ADAQN/AkACQAJAAkAjAg4DAAECAwtBASQCQQAkAxAGIwYkBSMDDwsjB0UhASMFEAQhAANAIwYgAEcEQCAAJAUgABAFIAFHBEAgACABEAdBACQDIABBFGoQMyMDDwsgABAEIQAMAQsLQQAkAxAGIwUQBCMGRgRAIw4hAANAIABBrMEBSQRAIAAoAgAQDCAAQQRqIQAMAQsLIwUQBCEAA0AjBiAARwRAIAAQBSABRwRAIAAgARAHIABBFGoQMwsgABAEIQAMAQsLIwghACMGJAggACQGIAEkByAAEAQkBUECJAILIwMPCyMFIgAjBkcEQCAAEAQkBSAAEAUjB0VHBEBBAEGQDEHkAUEUEAAACyAAQazBAUkEQCAAQQAQASAAQQAQAgUjACAAEA1rJAAgAEEEaiIBQazBAU8EQCMJRQRAEBILIwkhAiABQQRrIQAgAUEPcUEBIAEbBH9BAQUgACgCAEEBcQsEQEEAQaAOQa8EQQMQAAALIAAgACgCAEEBchAOIAIgABAQCwtBCg8LIwYjBhABIwYjBhACQQAkAgtBAAvUAQECfyABQYACSQR/IAFBBHYFQR9BAUEbIAFna3QgAWpBAWsgASABQf7///8BSRsiAWdrIgNBB2shAiABIANBBGt2QRBzCyIBQRBJIAJBF0lxRQRAQQBBoA5BygJBDhAAAAsgAkECdCAAaigCBEF/IAF0cSIBBH8gAWggAkEEdGpBAnQgAGooAmAFIAAoAgBBfyACQQFqdHEiAQR/IAFoIgFBAnQgAGooAgQiAkUEQEEAQaAOQdcCQRIQAAALIAJoIAFBBHRqQQJ0IABqKAJgBUEACwsL2gIBA38gAUH8////A0sEQEHQC0GgDkHKA0EdEAAACyAAQQwgAUETakFwcUEEayABQQxNGyIDEBQiAUUEQD8AIgFBBCAAKAKgDCABQRB0QQRrR3RBAUEbIANna3RBAWsgA2ogAyADQf7///8BSRtqQf//A2pBgIB8cUEQdiICIAEgAkobQABBAEgEQCACQABBAEgEQAALCyAAIAFBEHQ/AEEQdBARIAAgAxAUIgFFBEBBAEGgDkHwA0EQEAAACwsgASgCAEF8cSADSQRAQQBBoA5B8gNBDhAAAAsgACABEA8gASgCACEEIANBBGpBD3EEQEEAQaAOQeUCQQ4QAAALIARBfHEgA2siAkEQTwRAIAEgBEECcSADchAOIAMgAUEEamoiAyACQQRrQQFyEA4gACADEBAFIAEgBEF+cRAOIAFBBGogASgCAEF8cWoiACAAKAIAQX1xEA4LIAELCQAgACABNgIMCwkAIAAgATYCEAvIAQECfyAAQez///8DTwRAQdALQZAMQYQCQR8QAAALIwAjAU8EQAJAQYAQIQIDQCACEBNrIQIjAkUEQCMArULIAX5C5ACAp0GACGokAQwCCyACQQBKDQALIwAjACMBa0GACElBCnRqJAELCyMJRQRAEBILIwkgAEEQahAVIgIgARAWIAIgABAXIAIjCCMHEAojACACEA1qJAAgAkEUaiIDIQEgACECA0AgAgRAIAEiAEEBaiEBIABBADoAACACQQFrIQIMAQsLIAMLZwECfwJAIAIhBCAAIAFGDQAgACABSQRAA0AgBARAIAAiAkEBaiEAIAEiA0EBaiEBIAIgAy0AADoAACAEQQFrIQQMAQsLBQNAIAQEQCAEQQFrIgQgAGogASAEai0AADoAAAwBCwsLCwtDAQJ/IABBFGsiAygCAEF8cUEQayABTwRAIAMgARAXIAAPCyABIAMoAgwQGCICIAAgASADKAIQIgAgACABSxsQGSACC1sBAX8gAUUEQA8LIABFBEBBAEGQDEGmAkEOEAAACyABQRRrIgEQBSMHRgRAIABBFGsiABAFIgMjB0VGBEAgACABIAIbEAsFIwJBAUYgA0EDRnEEQCABEAsLCwsL6QIBBn8jDkEIayQOEDYjDkIANwMAPwBBEHRBrMEBa0EBdiQBQcAMEAMkBEHgDBADJAZB8A0QAyQIA0AgAEGAAkgEQCMOQaALNgIAQQEkCiMOQQRrJA4QNiMOQQA2AgAjDkECQQEQGCIBNgIAIAEgADsBACMOQQRqJA4jDiABNgIEQawLKAIAIABNBEAgAEEASARAQZANQeAOQYIBQRYQAAALIABBAWoiAiIEQagLKAIAIgVBAnZLBEAgBEH/////AEsEQEGQD0HgDkETQTAQAAALQaALKAIAIgMgBUEBdCIFQfz///8DIAVB/P///wNJGyIFIARBCCAEQQhLG0ECdCIEIAQgBUkbIgQQGiIFIANHBEBBoAsgBTYCAEGkCyAFNgIAQaALIAVBABAbC0GoCyAENgIAC0GgCyACEBYLQaQLKAIAIABBAnRqIAE2AgBBoAsgAUEBEBsgAEEBaiEADAELCyMOQQhqJA4LCQAgACABOwEACxEAIAAgATYCACAAIAFBABAbCxEAIAAgATYCECAAIAFBABAbCwoAIABBFGsoAhALigEBAn8CQAJAAkAjCkEBaw4DAQECAAsACyAAECAhAgsjDkEEayQOEDYjDkEANgIAIw5BDEEGEBgiATYCACABQQAQHiABQQAQASABQQAQAiAAECAgAkkgAkH8////A0tyBEBBkA9BgBBBGUEHEAAACyABIAAQHiABIAAQASABIAIQAiMOQQRqJA4gAQsRACAAIAE2AhQgACABQQAQGws1ACABQQBIBEBB4AhBwBBBOEEHEAAACyAAKAIEIAFIBEBBkApBwBBBPEEHEAAACyAAIAEQAgtLACACQQBIBEBBkA1BgBFB9A5BExAAAAsgACgCCCACIAEoAghqSARAQZANQYARQfUOQS8QAAALIAIgACgCBGogASgCBCABKAIIEBkLDgAgACABIAAoAghqECMLIQAgACgCBCABIAAoAghqSARAQaAJQcAQQawBQQcQAAALCxIAIABBCHQgAEH//wNxQQh2cgsZACAAQYD+g3hxQQh3IABB/4H8B3FBCHhyC0MAIABCCIhC/4H8h/CfwP8AgyAAQv+B/Ifwn8D/AINCCIaEIgBCEIhC//+DgPD/P4MgAEL//4OA8P8/g0IQhoRCIIoLDQAgAEEUaygCEEEBdguDAgEFfyAAIgFBCHYiAkG0NGotAAAgAkH8F2otAABB1gBsQfwXaiAAQf8BcSIDQQNuai0AACADQQNwQQJ0QegsaigCAGxBC3ZBBnBqQQJ0QfQsaigCACICQf8BcSEAIAJBCHUhAgJAIABBAkkNACACQf8BcSEAIAJBCHYhAgNAIAAEQCADIABBAXYiBSACakEBdEG0OGotAAAiBEYEfyACIAVqQQF0QbQ4ai0AAUECdEH0LGooAgAiAkH/AXEhACACQQh1IQIgAEECSQ0DIAFBAWsPBSADIARJBH8gBQUgAiAFaiECIAAgBWsLCyEADAELCyABDwtBACAAQQFzayACcSABagtzAQR/IAAgAUYEQEEBDwsgAUEAIAAbRQRAQQAPCyAAECohAiABECogAkcEQEEADwsCQANAIAIiA0EBayECIAMEQCAALwEAIgUgAS8BACIDayEEIAMgBUcNAiAAQQJqIQAgAUECaiEBDAELC0EAIQQLIARFC7ICAQJ/IAFBAXQgAGohAyACIQEDQCAAIANJBEAgAC8BACICQYABSQR/IAEgAjoAACABQQFqBSACQYAQSQR/IAEgAkEGdkHAAXIgAkE/cUGAAXJBCHRyOwEAIAFBAmoFIAJBgLgDSSADIABBAmpLcSACQYDwA3FBgLADRnEEQCAALwECIgRBgPgDcUGAuANGBEAgASACQf8HcUEKdEGAgARqIARB/wdxciICQT9xQYABckEYdCACQQZ2QT9xQYABckEQdHIgAkEMdkE/cUGAAXJBCHRyIAJBEnZB8AFycjYCACABQQRqIQEgAEEEaiEADAULCyABIAJBDHZB4AFyIAJBBnZBP3FBgAFyQQh0cjsBACABIAJBP3FBgAFyOgACIAFBA2oLCyEBIABBAmohAAwBCwsLaQEDfyMOQQRrJA4QNiMOQQA2AgACQCAAIgIQKkEBdCIDIAEQKkEBdCIEaiIARQRAIw5BBGokDkGQPiEADAELIw4gAEEBEBgiADYCACAAIAIgAxAZIAAgA2ogASAEEBkjDkEEaiQOCyAAC3sAAkACQAJAAkAjCkEBaw4DAQIDAAsAC0EAIQILIAEoAgghAwsjDkEIayQOEDYjDkIANwMAIw4gASACIAMQQyIBNgIAIAEoAggiAkEASgRAIAAgAhA4Iw4gACgCECIDNgIEIAMgASAAKAIIECQgACACECULIw5BCGokDgs0AQF/IAAEQCAAQRRrIgEQBUEDRgRAQfA/QZAMQdECQQcQAAALIAEQCSABIwRBAxAKCyAAC0AAIABFBEAPCyAAQRRrIgAQBUEDRwRAQbDAAEGQDEHfAkEFEAAACyMCQQFGBEAgABALBSAAEAkgACMIIwcQCgsLOQAjAkEASgRAA0AjAgRAEBMaDAELCwsQExoDQCMCBEAQExoMAQsLIwCtQsgBfkLkAICnQYAIaiQBC5gBAQN/AkACQAJAAkACQAJAAkAgAEEIaygCAA4JAAEGAgYDBgYEBQsPCw8LIAAoAgQiASAAKAIMQQJ0aiECA0AgASACSQRAIAEoAgAiAwRAIAMQDAsgAUEEaiEBDAELCyAAKAIAEAwPCyAAKAIQIgEEQCABEAwLIAAoAhQiAARAIAAQDAsPCw8LAAsgACgCACIABEAgABAMCwsGACAAJAoLBAAQHAsbACMOQazBAEgEQEHAwQFB8MEBQQFBARAAAAsLpAEAIw5BCGskDhA2Iw5CADcDACAARQRAIw5BGEEFEBgiADYCAAsgAEEAEB0gAEEAEAEgAEEAEAIgAEEAEBYgAEEAEB8gAEEAECIgACACEB0gACACQf//A3EgAUgEfyABIAJB//8DcSIBbbebqiABbAUgAQsQFiAAIAAoAgwQQRAfIw4gACgCECgCACIBNgIEQQEkCiAAIAEQIRAiIw5BCGokDiAAC7IBAQJ/Iw5BDGskDhA2Iw5CADcDACMOQQA2AgggAUEASgRAIAAoAgggAWohASMOIAAoAhAiAjYCACACKAIIIAFIBEAjDiABIAAvAQAiAkoEfyACIAEgAm23m6psBSABCxBBIgI2AgQjDiAAKAIQIgM2AgggAiADQQAQJCAAIAIQHyMOIAIoAgAiAjYCCEEBJAogACACECEQIgsgACgCBCABSARAIAAgARABCwsjDkEMaiQOCzYBAX8jDkEEayQOEDYjDkEANgIAIw4gACgCECIBNgIAIAFBACAAKAIEEEIhACMOQQRqJA4gAAteAQJ/Iw5BBGskDhA2Iw5BADYCACAAQQEQOCMOIAAoAhQiAjYCACAAKAIIIgMgAigCCE8EQEGQDUGAEEGAAUEyEAAACyADIAIoAgRqIAE6AAAgAEEBECUjDkEEaiQOC7MEAQp/Iw5BCGskDhA2Iw5CADcDACAAECoiBkUEQCMOQQhqJA4gAA8LIw4gBkEGbEEBEBgiCDYCACMOQcARNgIEQcARECohAgNAIAYgB0sEQCAHQQF0IABqLwEAIgNBB3YEQAJAIANB/68Da0GBCEkgBkEBayAHS3EEQCAHQQF0IABqLwECIgRB/7cDa0GBCEkEQCAHQQFqIQcgBEH/B3EgAyIBQf8HcUEKdHJBgIAEaiIDQYCACE8EQCAJQQF0IAhqIARBEHQgAXI2AgAgCUEBaiEJDAMLCwsgA0HQyQBrQRlNBEAgCUEBdCAIaiADQRprOwEABUF/IQogA0HfAWtBuPQDTQRAAkAgAiEBQQAhBQNAIAEgBU4EQCABIAVqQQN2QQJ0IgpBAXRBwBFqLwEAIANrIgRFDQIgBEEfdgRAIApBBGohBQUgCkEEayEBCwwBCwtBfyEKCwsgCkF/cwRAIApBAXRBwBFqIgQvAQYhAyAJQQF0IAhqIgEgBCgCAjYCACABIAM7AQQgA0EAR0EBaiAJaiEJBSADECtB////AHEiAUGAgARJBEAgCUEBdCAIaiABOwEABSAJQQF0IAhqIAFBgIAEayIBQQp2QYCwA3IgAUH/B3FBgLgDckEQdHI2AgAgCUEBaiEJCwsLCwUgCUEBdCAIaiADQeEAa0EaSUEFdEF/cyADcTsBAAsgB0EBaiEHIAlBAWohCQwBCwsgCCAJQQF0EBohACMOQQhqJA4gAAvyAwEDfyMOQRBrJA4QNiMOQgA3AwAjDkIANwMIIAAhAyMOIAIQOyIANgIEIw5B4Ds2AggCQCAAQeA7ECwEf0EBBSMOQYA8NgIIIABBgDwQLAsEQEEBJAojDkEEayQOEDYjDkEANgIAIw4Cf0EAIQIgASIAQRRrKAIQIABqIQQDQCAAIARJBEAgAC8BACIFQYABSQR/IAJBAWoFIAVBgBBJBH8gAkECagUgBUGA+ANxQYCwA0YgBCAAQQJqS3EEQCAALwECQYD4A3FBgLgDRgRAIAJBBGohAiAAQQRqIQAMBQsLIAJBA2oLCyECIABBAmohAAwBCwsgAgtBABAYIgA2AgAgASABECogABAtDAELIw5BkD02AgggAEGQPRAsBH9BAQUjDkGwPTYCCCAAQbA9ECwLBEAjDkEEayQOEDYjDkEANgIAIw4gARAgQQAQGCIANgIAIAAgASABECpBAXQQGQwBCyMOQdA9NgIMQdA9IAIQLkGwPkEZQQMQAAALIw5BBGokDiMOIAA2AgBBASQKIw5BBGskDhA2Iw5BADYCACAAECAhASMOQQxBBBAYIgI2AgAgAiAANgIAIAIgAEEAEBsgAiABNgIIIAIgADYCBCMOQQRqJA4jDiACNgIAQQEkCiADIAJBAEEAEC8jDkEQaiQOC2ABAn8jDkEEayQOEDYjDkEANgIAIABBARAmIw4gACgCFCIBNgIAIAAoAggiAiABKAIITwRAQZANQYAQQcgAQTIQAAALIAIgASgCBGotAAAhASAAQQEQJSMOQQRqJA4gAQtrAQJ/Iw5BCGskDhA2Iw5CADcDACABQQBOBEAgASAAKAIIaiICIAAoAgRMBEAjDiAAKAIQIgM2AgAjDiADIAAoAgggAhBCIgI2AgQgACABECUjDkEIaiQOIAIPCwtBoAlBwBBB/wNBBRAAAAvsAQAjDkEQayQOEDYjDkIANwMAIw5CADcDCCMOIAAgARA+KAIAIgE2AgAjDiACEDsiADYCBCMOQeA7NgIIAkAgAEHgOxAsBH9BAQUjDkGAPDYCCCAAQYA8ECwLBEAgASABECAQRCEADAELIw5BkD02AgggAEGQPRAsBH9BAQUjDkGwPTYCCCAAQbA9ECwLBEAgARAgIQAjDkEEayQOEDYjDkEANgIAIw4gAEF+cSICQQEQGCIANgIAIAAgASACEBkjDkEEaiQODAELIw5B0D02AgxB0D0gAhAuQbA+QTBBAxAAAAsjDkEQaiQOIAAL+AEBBX8jDkEMayQOEDYjDkIANwMAIw5BADYCCEGQPiECIw5BkD42AgAjDiAAEDkiBDYCBCAEKAIIIQADQCAAIAFKBEAjDiEDIw5BoAs2AgggBCgCCCABTQRAQZANQYARQaYBQS0QAAALIAEgBCgCBGotAAAhBSMOQQRrJA4QNiMOQQA2AgBBrAsoAgAgBU0EQEGQDUHgDkHyAEEqEAAACyMOQaQLKAIAIAVBAnRqKAIAIgU2AgAgBUUEQEHwPkHgDkH2AEEoEAAACyMOQQRqJA4jDiAFNgIIIAMgAiAFEC4iAjYCACABQQFqIQEMAQsLIw5BDGokDiACC6kBAQN/Iw5BBGskDhA2Iw5BADYCACMOQQxBBBAYIgE2AgAjDiEDIw5BCGskDhA2Iw5CADcDACABRQRAIw5BDEECEBgiATYCAAsgAUEAEB4gAUEAEAEgAUEAEAIgAEH8////A0sEQEGQD0HAD0ETQTkQAAALIw4gAEEAEBgiAjYCBCABIAIQHiABIAIQASABIAAQAiMOQQhqJA4gAyABNgIAIw5BBGokDiABC5MBAQF/Iw5BBGskDhA2Iw5BADYCACAAKAIIIQMgAUEASAR/IAEgA2oiAUEAIAFBAEobBSABIAMgASADSBsLIQEjDiACQQBIBH8gAiADaiICQQAgAkEAShsFIAIgAyACIANIGwsgAWsiAkEAIAJBAEobIgIQQSIDNgIAIAMoAgQgASAAKAIEaiACEBkjDkEEaiQOIAMLqAEBA38jDkEEayQOEDYjDkEANgIAIAAoAgghAyMOQQxBBBAYIgU2AgAgBSAAKAIAIgQ2AgAgBSAEQQAQGyAFIAAoAgQgAUEASAR/IAEgA2oiAEEAIABBAEobBSABIAMgASADSBsLIgBqNgIEIAUgAkEASAR/IAIgA2oiAUEAIAFBAEobBSACIAMgAiADSBsLIgEgACAAIAFIGyAAazYCCCMOQQRqJA4gBQvmAgEFfyMOQQRrJA4QNiMOQQA2AgAgACAAIAFqIgRLBEBBAEHgPEGBBkEHEAAACyMOIAFBAXRBARAYIgI2AgAgAiEBA0AgACAESQRAAkAgAC0AACEFIABBAWohACAFQYABcQRAIAAgBEYNASAALQAAQT9xIQYgAEEBaiEAIAVB4AFxQcABRgRAIAEgBiAFQR9xQQZ0cjsBAAUgACAERg0CIAAtAABBP3EhAyAAQQFqIQAgBUHwAXFB4AFGBEAgAyAFQQ9xQQx0IAZBBnRyciEDBSAAIARGDQMgAC0AAEE/cSAFQQdxQRJ0IAZBDHRyIANBBnRyciEDIABBAWohAAsgA0GAgARJBEAgASADOwEABSABIANBgIAEayIDQQp2QYCwA3IgA0H/B3FBgLgDckEQdHI2AgAgAUECaiEBCwsFIAEgBTsBAAsgAUECaiEBDAILCwsgAiABIAJrEBohACMOQQRqJA4gAAtDACMOQQRrJA4QNiMOIAA2AgACQAJAAkACQCMKDgMBAgMACwALQQAhAQtBgCAhAgsgACABIAIQNyEAIw5BBGokDiAACyIAIw5BBGskDhA2Iw4gADYCACAAKAIIIQAjDkEEaiQOIAALHwAjDkEEayQOEDYjDiAANgIAIAAgARAjIw5BBGokDgsiACMOQQRrJA4QNiMOIAA2AgAgACgCBCEAIw5BBGokDiAAC4MBAQF/Iw5BBGskDhA2Iw4gADYCACMOQQRrJA4QNiMOQQA2AgAgAUEASARAQaAIQcAQQdUAQQcQAAALIw4gACgCECICNgIAIAIoAgggAUgEQCAAIAEgACgCCGsQOAUgACABEAELIAEgACgCCEgEQCAAIAEQAgsjDkEEaiQOIw5BBGokDgu4AQEDfyMOQQRrJA4QNiMOIAA2AgAjDkEEayQOEDYjDkEANgIAIw4gACgCECgCACIBNgIAIAAoAgQhAiMOQQRrJA4QNiMOQQA2AgBBACABECAiAyADQQBKGyEAIw4gAkEASAR/IAIgA2oiAkEAIAJBAEobBSACIAMgAiADSBsLIABrIgJBACACQQBKGyICQQAQGCIDNgIAIAMgACABaiACEBkjDkEEaiQOIw5BBGokDiMOQQRqJA4gAwshACMOQQRrJA4QNiMOIAA2AgAgABA5IQAjDkEEaiQOIAALHwAjDkEEayQOEDYjDiAANgIAIAAgARA4Iw5BBGokDgsfACMOQQRrJA4QNiMOIAA2AgAgACABECUjDkEEaiQOCx8AIw5BBGskDhA2Iw4gADYCACAAIAEQJiMOQQRqJA4LdQECfyMOQQRrJA4QNiMOIAA2AgAjDkEEayQOEDYjDkEANgIAIABBARA4Iw4gACgCFCICNgIAIAAoAggiAyACKAIITwRAQZANQYAQQe0AQTIQAAALIAMgAigCBGogAToAACAAQQEQJSMOQQRqJA4jDkEEaiQOCx8AIw5BBGskDhA2Iw4gADYCACAAIAEQOiMOQQRqJA4LIQAjDkEEayQOEDYjDiAANgIAIAAgAUVFEDojDkEEaiQOC6ABAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEECEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEECakhyBEBBkA1BgBBB9ABBBxAAAAsgBCADKAIEaiACBH8gAQUgARAnCzsBACAAQQIQJSMOQQRqJA4jDkEEaiQOC6ABAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEECEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEECakhyBEBBkA1BgBBBhwFBBxAAAAsgBCADKAIEaiACBH8gAQUgARAnCzsBACAAQQIQJSMOQQRqJA4jDkEEaiQOC6ABAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEEEEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEEakhyBEBBkA1BgBBB+wBBBxAAAAsgBCADKAIEaiACBH8gAQUgARAoCzYCACAAQQQQJSMOQQRqJA4jDkEEaiQOC6ABAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEEEEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEEakhyBEBBkA1BgBBBjgFBBxAAAAsgBCADKAIEaiACBH8gAQUgARAoCzYCACAAQQQQJSMOQQRqJA4jDkEEaiQOC6ABAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEEIEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEIakhyBEBBkA1BgBBBpwFBBxAAAAsgBCADKAIEaiACBH4gAQUgARApCzcDACAAQQgQJSMOQQRqJA4jDkEEaiQOC6ABAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEEIEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEIakhyBEBBkA1BgBBBrgFBBxAAAAsgBCADKAIEaiACBH4gAQUgARApCzcDACAAQQgQJSMOQQRqJA4jDkEEaiQOC6wBAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEEEEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEEakhyBEBBkA1BgBBB3wBBBxAAAAsgAgRAIAQgAygCBGogATgCAAUgBCADKAIEaiABvBAoNgIACyAAQQQQJSMOQQRqJA4jDkEEaiQOC6wBAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKQQFrDgIBAgALAAtBACECCyMOQQRrJA4QNiMOQQA2AgAgAEEIEDgjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEIakhyBEBBkA1BgBBB5wBBBxAAAAsgAgRAIAQgAygCBGogATkDAAUgBCADKAIEaiABvRApNwMACyAAQQgQJSMOQQRqJA4jDkEEaiQOCyoAIw5BCGskDhA2Iw4gADYCACMOIAE2AgQgACABIAIgAxAvIw5BCGokDgtnACMOQQxrJA4QNiMOIAA2AgAjDiABNgIEIw4gAjYCCCMOQQRrJA4QNiMOQQA2AgACQAJAAkAjCkEBaw4CAQIACwALQeA7IQIjDkHgOzYCAAsgACABIAIQPCMOQQRqJA4jDkEMaiQOC3YBAn8jDkEEayQOEDYjDiAANgIAIw5BBGskDhA2Iw5BADYCACAAQQEQJiMOIAAoAhQiAjYCACAAKAIIIgEgAigCCE8EQEGQDUGAEEEzQTIQAAALIAEgAigCBGosAAAhASAAQQEQJSMOQQRqJA4jDkEEaiQOIAELIQAjDkEEayQOEDYjDiAANgIAIAAQPSEAIw5BBGokDiAACyQAIw5BBGskDhA2Iw4gADYCACAAED1BAEchACMOQQRqJA4gAAuhAQECfyMOQQRrJA4QNiMOIAA2AgACQAJAAkAjCg4CAQIACwALQQAhAQsjDkEEayQOEDYjDkEANgIAIABBAhAmIw4gACgCFCICNgIAIAAoAggiA0EfdiACKAIIIANBAmpIcgRAQZANQYAQQTpBBxAAAAsgAyACKAIEai4BACECIAFFBEAgAhAnIQILIABBAhAlIw5BBGokDiMOQQRqJA4gAsELpgEBAn8jDkEEayQOEDYjDiAANgIAAkACQAJAIwoOAgECAAsAC0EAIQELIw5BBGskDhA2Iw5BADYCACAAQQIQJiMOIAAoAhQiAjYCACAAKAIIIgNBH3YgAigCCCADQQJqSHIEQEGQDUGAEEHPAEEHEAAACyADIAIoAgRqLwEAIQIgAUUEQCACECchAgsgAEECECUjDkEEaiQOIw5BBGokDiACQf//A3ELoQEBAn8jDkEEayQOEDYjDiAANgIAAkACQAJAIwoOAgECAAsAC0EAIQELIw5BBGskDhA2Iw5BADYCACAAQQQQJiMOIAAoAhQiAjYCACAAKAIIIgNBH3YgAigCCCADQQRqSHIEQEGQDUGAEEHCAEEHEAAACyADIAIoAgRqKAIAIQIgAUUEQCACECghAgsgAEEEECUjDkEEaiQOIw5BBGokDiACC6EBAQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKDgIBAgALAAtBACEBCyMOQQRrJA4QNiMOQQA2AgAgAEEEECYjDiAAKAIUIgI2AgAgACgCCCIDQR92IAIoAgggA0EEakhyBEBBkA1BgBBB1wBBBxAAAAsgAyACKAIEaigCACECIAFFBEAgAhAoIQILIABBBBAlIw5BBGokDiMOQQRqJA4gAgujAQIBfgJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKDgIBAgALAAtBACEBCyMOQQRrJA4QNiMOQQA2AgAgAEEIECYjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEIakhyBEBBkA1BgBBBlwFBBxAAAAsgBCADKAIEaikDACECIAFFBEAgAhApIQILIABBCBAlIw5BBGokDiMOQQRqJA4gAgujAQIBfgJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKDgIBAgALAAtBACEBCyMOQQRrJA4QNiMOQQA2AgAgAEEIECYjDiAAKAIUIgM2AgAgACgCCCIEQR92IAMoAgggBEEIakhyBEBBkA1BgBBBnwFBBxAAAAsgBCADKAIEaikDACECIAFFBEAgAhApIQILIABBCBAlIw5BBGokDiMOQQRqJA4gAguqAQIBfQJ/Iw5BBGskDhA2Iw4gADYCAAJAAkACQCMKDgIBAgALAAtBACEBCyMOQQRrJA4QNiMOQQA2AgAgAEEEECYjDiAAKAIUIgQ2AgAgACgCCCIDQR92IAQoAgggA0EEakhyBEBBkA1BgBBBI0EHEAAACyABBH0gAyAEKAIEaioCAAUgAyAEKAIEaigCABAovgshAiAAQQQQJSMOQQRqJA4jDkEEaiQOIAILqgECAXwCfyMOQQRrJA4QNiMOIAA2AgACQAJAAkAjCg4CAQIACwALQQAhAQsjDkEEayQOEDYjDkEANgIAIABBCBAmIw4gACgCFCIENgIAIAAoAggiA0EfdiAEKAIIIANBCGpIcgRAQZANQYAQQSxBBxAAAAsgAQR8IAMgBCgCBGorAwAFIAMgBCgCBGopAwAQKb8LIQIgAEEIECUjDkEEaiQOIw5BBGokDiACCyMAIw5BBGskDhA2Iw4gADYCACAAIAEQPiEAIw5BBGokDiAAC2QAIw5BCGskDhA2Iw4gADYCACMOIAI2AgQjDkEEayQOEDYjDkEANgIAAkACQAJAIwpBAWsOAgECAAsAC0HgOyECIw5B4Ds2AgALIAAgASACED8hACMOQQRqJA4jDkEIaiQOIAALIQAjDkEEayQOEDYjDiAANgIAIAAQQCEAIw5BBGokDiAAC2QBAX8jDkEEayQOEDYjDiAANgIAIw5BBGskDhA2Iw5BADYCACAAQQAQAiAAQQAQASAAIAAoAgwQQRAfIw4gACgCECgCACIBNgIAQQEkCiAAIAEQIRAiIw5BBGokDiMOQQRqJA4LC6otWwBBjAgLATwAQZgICzEBAAAAKgAAAEkAbgB2AGEAbABpAGQAIABiAHUAZgBmAGUAcgAgAGwAZQBuAGcAdABoAEHMCAsBPABB2AgLMQEAAAAqAAAASQBuAHYAYQBsAGkAZAAgAGIAdQBmAGYAZQByACAAbwBmAGYAcwBlAHQAQYwJCwFsAEGYCQtXAQAAAFAAAABSAGUAYQBkACAAaQBzACAAbwB1AHQAcwBpAGQAZQAgAHQAaABlACAAYgBvAHUAbgBkAHMAIABvAGYAIAB0AGgAZQAgAEIAdQBmAGYAZQByAEH8CQsBbABBiAoLWwEAAABUAAAATwBmAGYAcwBlAHQAIABpAHMAIABvAHUAdABzAGkAZABlACAAdABoAGUAIABiAG8AdQBuAGQAcwAgAG8AZgAgAHQAaABlACAAQgB1AGYAZgBlAHIAQewKCwEcAEGMCwsBLABBmAsLDgMAAAAQAAAAgAUAAIAFAEG8CwsBPABByAsLLwEAAAAoAAAAQQBsAGwAbwBjAGEAdABpAG8AbgAgAHQAbwBvACAAbABhAHIAZwBlAEH8CwsBPABBiAwLJwEAAAAgAAAAfgBsAGkAYgAvAHIAdAAvAGkAdABjAG0AcwAuAHQAcwBB/AwLATwAQYgNCysBAAAAJAAAAEkAbgBkAGUAeAAgAG8AdQB0ACAAbwBmACAAcgBhAG4AZwBlAEG8DQsBLABByA0LGwEAAAAUAAAAfgBsAGkAYgAvAHIAdAAuAHQAcwBBjA4LATwAQZgOCyUBAAAAHgAAAH4AbABpAGIALwByAHQALwB0AGwAcwBmAC4AdABzAEHMDgsBLABB2A4LIQEAAAAaAAAAfgBsAGkAYgAvAGEAcgByAGEAeQAuAHQAcwBB/A4LASwAQYgPCyMBAAAAHAAAAEkAbgB2AGEAbABpAGQAIABsAGUAbgBnAHQAaABBrA8LATwAQbgPCy0BAAAAJgAAAH4AbABpAGIALwBhAHIAcgBhAHkAYgB1AGYAZgBlAHIALgB0AHMAQewPCwE8AEH4DwsnAQAAACAAAAB+AGwAaQBiAC8AZABhAHQAYQB2AGkAZQB3AC4AdABzAEGsEAsBPABBuBALKQEAAAAiAAAAYQBzAHMAZQBtAGIAbAB5AC8AaQBuAGQAZQB4AC4AdABzAEHsEAsBPABB+BALKwEAAAAkAAAAfgBsAGkAYgAvAHQAeQBwAGUAZABhAHIAcgBhAHkALgB0AHMAQawRCwJMAwBBuBELtgYIAAAAMAMAAN8AUwBTAAAASQG8Ak4AAADwAUoADAMAAJADmQMIAwEDsAOlAwgDAQOHBTUFUgUAAJYeSAAxAwAAlx5UAAgDAACYHlcACgMAAJkeWQAKAwAAmh5BAL4CAABQH6UDEwMAAFIfpQMTAwADVB+lAxMDAQNWH6UDEwNCA4AfCB+ZAwAAgR8JH5kDAACCHwofmQMAAIMfCx+ZAwAAhB8MH5kDAACFHw0fmQMAAIYfDh+ZAwAAhx8PH5kDAACIHwgfmQMAAIkfCR+ZAwAAih8KH5kDAACLHwsfmQMAAIwfDB+ZAwAAjR8NH5kDAACOHw4fmQMAAI8fDx+ZAwAAkB8oH5kDAACRHykfmQMAAJIfKh+ZAwAAkx8rH5kDAACUHywfmQMAAJUfLR+ZAwAAlh8uH5kDAACXHy8fmQMAAJgfKB+ZAwAAmR8pH5kDAACaHyofmQMAAJsfKx+ZAwAAnB8sH5kDAACdHy0fmQMAAJ4fLh+ZAwAAnx8vH5kDAACgH2gfmQMAAKEfaR+ZAwAAoh9qH5kDAACjH2sfmQMAAKQfbB+ZAwAApR9tH5kDAACmH24fmQMAAKcfbx+ZAwAAqB9oH5kDAACpH2kfmQMAAKofah+ZAwAAqx9rH5kDAACsH2wfmQMAAK0fbR+ZAwAArh9uH5kDAACvH28fmQMAALIfuh+ZAwAAsx+RA5kDAAC0H4YDmQMAALYfkQNCAwAAtx+RA0IDmQO8H5EDmQMAAMIfyh+ZAwAAwx+XA5kDAADEH4kDmQMAAMYflwNCAwAAxx+XA0IDmQPMH5cDmQMAANIfmQMIAwAD0x+ZAwgDAQPWH5kDQgMAANcfmQMIA0ID4h+lAwgDAAPjH6UDCAMBA+QfoQMTAwAA5h+lA0IDAADnH6UDCANCA/If+h+ZAwAA8x+pA5kDAAD0H48DmQMAAPYfqQNCAwAA9x+pA0IDmQP8H6kDmQMAAAD7RgBGAAAAAftGAEkAAAAC+0YATAAAAAP7RgBGAEkABPtGAEYATAAF+1MAVAAAAAb7UwBUAAAAE/tEBUYFAAAU+0QFNQUAABX7RAU7BQAAFvtOBUYFAAAX+0QFPQUAQfwXC4AEBwgJCgsMBgYGBgYGBgYGBg0GBg4GBgYGBgYGBg8QERIGEwYGBgYGBgYGBgYUFQYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBhYXBgYGGAYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGGQYGBgYaBgYGBgYGBhsGBgYGBgYGBgYGBhwGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGHQYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGHgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYAQescCxQkKysrKysrKysBAFRWVlZWVlZWVgBBkh0LnwMYAAAAKysrKysrKwcrK1tWVlZWVlZWSlZWBTFQMVAxUDFQMVAxUDFQMVAkUHkxUDFQMThQMVAxUDFQMVAxUDFQMVBOMQJODQ1OA04AJG4ATjEmblFOJFBOORSBGx0dUzFQMVANMVAxUDFQG1MkUDECXHtce1x7XHtcexR5XHtce1wtK0kDSAN4XHsUAJYKASsoBgYAKgYqKisHu7UrHgArBysrKwErKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKwErKysrKysrKysrKysrKysrKysrKysrKyorKysrKysrKysrKysrzUbNKwAlKwcBBgFVVlZWVlZVVlYCJIGBgYGBFYGBgQAAKwCy0bLRstGy0QAAzcwBANfX19fXg4GBgYGBgYGBgYGsrKysrKysrKysHAAAAAAAMVAxUDFQMVAxUDECAAAxUDFQMVAxUDFQMVAxUDFQMVBOMVAxUE4xUDFQMVAxUDFQMVAxUDECh6aHpoemh6aHpoemh6aHpiorKysrKysrKysrKysAAABUVlZWVlZWVlZWVlZWAEGPIQshVFZWVlZWVlZWVlZWVgwADCorKysrKysrKysrKysrByoBAEHlIQt3KisrKysrKysrKysrKysrKysrKysrKysrKysrVlZsgRUAKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrB2wDQSsrVlZWVlZWVlZWVlZWVlYsVisrKysrKysrKysrKysrKysrKysrKwEAQYQjCwgMbAAAAAAABgBBsiML6AIGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJVZ6niYGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGJQYlBiUGASsrT1ZWLCt/VlY5KytVVlYrK09WViwrf1ZWgTd1W3tcKytPVlYCrAQAADkrK1VWVisrT1ZWLCsrVlYyE4FXAG+BfsnXfi2BgQ5+OX9vVwCBgX4VAH4DKysrKysrKysrKysrByskK5crKysrKysrKysqKysrKytWVlZWVoCBgYGBObsqKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKwGBgYGBgYGBgYGBgYGBgYHJrKysrKysrKysrKysrKys0A0ATjECtMHB19ckUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQMVAxUDFQ19dTwUfU19fXBSsrKysrKysrKysrKwcBAAEAQfUmCx9OMVAxUDFQMVAxUDFQMVANAAAAAAAkUDFQMVAxUDFQAEG2JwtWKysrKysrKysrKyt5XHtce097XHtce1x7XHtce1x7XHtce1x7XC0rK3kUXHtcLXkqXCdce1x7XHukAAq0XHtce08DeDgrKysrKysrKysrKysrTy0rKwEAQacoCwFIAEGxKAsbKisrKysrKysrKysrKysrKysrKysrKysrKysrAEHtKAsUKysrKysrKysHAEhWVlZWVlZWVgIAQbgpCxsrKysrKysrKysrKysrVVZWVlZWVlZWVlZWVg4AQfIpCxokKysrKysrKysrKysHAFZWVlZWVlZWVlZWVgBBuCoLJyQrKysrKysrKysrKysrKysrBwAAAABWVlZWVlZWVlZWVlZWVlZWVgBBmSsLFiorKysrKysrKysrVlZWVlZWVlZWVg4AQc8rCxYqKysrKysrKysrK1ZWVlZWVlZWVlYOAEGQLAsXKysrKysrKysrKytVVlZWVlZWVlZWVg4AQeksCwgIAABWAQAAOQBB+CwLvAcBIAAAAOD//wC/HQAA5wIAAHkAAAIkAAABAQAAAP///wAAAAABAgAAAP7//wE5//8AGP//AYf//wDU/v8AwwAAAdIAAAHOAAABzQAAAU8AAAHKAAABywAAAc8AAABhAAAB0wAAAdEAAACjAAAB1QAAAIIAAAHWAAAB2gAAAdkAAAHbAAAAOAAAAwAAAACx//8Bn///Acj//wIoJAAAAAAAAQEAAAD///8AM///ACb//wF+//8BKyoAAV3//wEoKgAAPyoAAT3//wFFAAABRwAAAB8qAAAcKgAAHioAAC7//wAy//8ANv//ADX//wBPpQAAS6UAADH//wAopQAARKUAAC///wAt//8A9ykAAEGlAAD9KQAAK///ACr//wDnKQAAQ6UAACqlAAC7//8AJ///ALn//wAl//8AFaUAABKlAAIkTAAAAAAAASAAAADg//8BAQAAAP///wBUAAABdAAAASYAAAElAAABQAAAAT8AAADa//8A2///AOH//wDA//8Awf//AQgAAADC//8Ax///ANH//wDK//8A+P//AKr//wCw//8ABwAAAIz//wHE//8AoP//Afn//wIacAABAQAAAP///wEgAAAA4P//AVAAAAEPAAAA8f//AAAAAAEwAAAA0P//AQEAAAD///8AAAAAAMALAAFgHAAAAAAAAdCXAAEIAAAA+P//AgWKAAAAAAABQPT/AJ7n/wDCiQAA2+f/AJLn/wCT5/8AnOf/AJ3n/wCk5/8AAAAAADiKAAAEigAA5g4AAQEAAAD///8AAAAAAMX//wFB4v8CHY8AAAgAAAH4//8AAAAAAFYAAAGq//8ASgAAAGQAAACAAAAAcAAAAH4AAAAJAAABtv//Aff//wDb4/8BnP//AZD//wGA//8Bgv//AgWsAAAAAAABEAAAAPD//wEcAAABAQAAAaPi/wFB3/8But//AOT//wILsQABAQAAAP///wEwAAAA0P//AAAAAAEJ1v8BGvH/ARnW/wDV1f8A2NX/AeTV/wED1v8B4dX/AeLV/wHB1f8AAAAAAKDj/wAAAAABAQAAAP///wIMvAAAAAAAAQEAAAD///8BvFr/AaADAAH8df8B2Fr/ADAAAAGxWv8BtVr/Ab9a/wHuWv8B1lr/Aeta/wHQ//8BvVr/Ach1/wAAAAAAMGj/AGD8/wAAAAABIAAAAOD//wAAAAABKAAAANj//wAAAAABQAAAAMD//wAAAAABIAAAAOD//wAAAAABIAAAAOD//wAAAAABIgAAAN7//wBBtTQLBQYnUW93AEHENAsSfAAAfwAAAAAAAAAAg46SlwCqAEHgNAsCtMQAQdo1CwbGyQAAANsAQbM2Cw7eAAAAAOEAAAAAAAAA5ABBzDYLAecAQaI3CwHqAEGdOAsB7QBBtDgLkAMwDDENeA5/D4AQgRGGEokTihOOFI8VkBaTE5QXlRiWGZcamhucGZ0cnh2fHqYfqR+uH7EgsiC3Ib8ixSPII8sj3STyI/Yl9yYgLTouPS8+MD8xQDFDMkQzRTRQNVE2UjdTOFQ5WTpbO1w8YT1jPmU/ZkBoQWlCakBrQ2xEb0JxRXJGdUd9SIJJh0qJS4pMi0yMTZJOnU+eUEVXex18HX0df1iGWYhaiVqKWoxbjlyPXKxdrV6uXq9ewl/MYM1hzmHPYtBj0WTVZdZm12fwaPFp8mrza/Rs9W35bv0t/i3/LVBpUWlSaVNpVGlVaVZpV2lYaVlpWmlbaVxpXWleaV9pggCDAIQAhQCGAIcAiACJAMB1z3aAiYGKgouFjIaNcJ1xnXaed554n3mfeqB7oHyhfaGzorqju6O8pL6lw6LMpNqm26blauqn66fsbvOi+Kj5qPqp+6n8pCawKrErsk6zhAhiumO7ZLxlvWa+bb9uwG/BcMJ+w3/Dfc+N0JTRq9Ks063UsNWx1rLXxNjF2cbaAEHMOwsBHABB2DsLDwEAAAAIAAAAVQBUAEYAOABB7DsLARwAQfg7CxEBAAAACgAAAFUAVABGAC0AOABBjDwLATwAQZg8CysBAAAAJAAAAFUAbgBwAGEAaQByAGUAZAAgAHMAdQByAHIAbwBnAGEAdABlAEHMPAsBLABB2DwLIwEAAAAcAAAAfgBsAGkAYgAvAHMAdAByAGkAbgBnAC4AdABzAEH8PAsBHABBiD0LEQEAAAAKAAAAVQBUAEYAMQA2AEGcPQsBHABBqD0LEwEAAAAMAAAAVQBUAEYALQAxADYAQbw9CwE8AEHIPQsxAQAAACoAAABVAG4AcwB1AHAAcABvAHIAdABlAGQAIABlAG4AYwBvAGQAaQBuAGcAIABB/D0LARwAQYg+CwEBAEGcPgsBPABBqD4LKQEAAAAiAAAAYQBzAHMAZQBtAGIAbAB5AC8AdQB0AGkAbABzAC4AdABzAEHcPgsBfABB6D4LZQEAAABeAAAARQBsAGUAbQBlAG4AdAAgAHQAeQBwAGUAIABtAHUAcwB0ACAAYgBlACAAbgB1AGwAbABhAGIAbABlACAAaQBmACAAYQByAHIAYQB5ACAAaQBzACAAaABvAGwAZQB5AEHcPwsBPABB6D8LMQEAAAAqAAAATwBiAGoAZQBjAHQAIABhAGwAcgBlAGEAZAB5ACAAcABpAG4AbgBlAGQAQZzAAAsBPABBqMAACy8BAAAAKAAAAE8AYgBqAGUAYwB0ACAAaQBzACAAbgBvAHQAIABwAGkAbgBuAGUAZABB4MAACw0JAAAAIAAAAAAAAAAgAEH8wAALDQJBAAAAAAAAQQAAAAIAQZzBAAsJQQAAAAIAAACk";

    // Runtime header offsets
    const ID_OFFSET = -8;
    const SIZE_OFFSET = -4;

    // Runtime ids
    const ARRAYBUFFER_ID = 0;
    const STRING_ID = 1;
    // const ARRAYBUFFERVIEW_ID = 2;

    // Runtime type information
    const ARRAYBUFFERVIEW = 1 << 0;
    const ARRAY = 1 << 1;
    const STATICARRAY = 1 << 2;
    // const SET = 1 << 3;
    // const MAP = 1 << 4;
    const VAL_ALIGN_OFFSET = 6;
    // const VAL_ALIGN = 1 << VAL_ALIGN_OFFSET;
    const VAL_SIGNED = 1 << 11;
    const VAL_FLOAT = 1 << 12;
    // const VAL_NULLABLE = 1 << 13;
    const VAL_MANAGED = 1 << 14;
    // const KEY_ALIGN_OFFSET = 15;
    // const KEY_ALIGN = 1 << KEY_ALIGN_OFFSET;
    // const KEY_SIGNED = 1 << 20;
    // const KEY_FLOAT = 1 << 21;
    // const KEY_NULLABLE = 1 << 22;
    // const KEY_MANAGED = 1 << 23;

    // Array(BufferView) layout
    const ARRAYBUFFERVIEW_BUFFER_OFFSET = 0;
    const ARRAYBUFFERVIEW_DATASTART_OFFSET = 4;
    const ARRAYBUFFERVIEW_BYTELENGTH_OFFSET = 8;
    const ARRAYBUFFERVIEW_SIZE = 12;
    const ARRAY_LENGTH_OFFSET = 12;
    const ARRAY_SIZE = 16;

    const E_NO_EXPORT_TABLE   = "Operation requires compiling with --exportTable";
    const E_NO_EXPORT_RUNTIME = "Operation requires compiling with --exportRuntime";
    const F_NO_EXPORT_RUNTIME = () => { throw Error(E_NO_EXPORT_RUNTIME); };

    const BIGINT = typeof BigUint64Array !== "undefined";
    const THIS = Symbol();

    const STRING_SMALLSIZE = 192; // break-even point in V8
    const STRING_CHUNKSIZE = 1024; // mitigate stack overflow
    const utf16 = new TextDecoder("utf-16le", { fatal: true }); // != wtf16

    /** polyfill for Object.hasOwn */
    Object.hasOwn = Object.hasOwn || function(obj, prop) {
      return Object.prototype.hasOwnProperty.call(obj, prop);
    };

    /** Gets a string from memory. */
    function getStringImpl(buffer, ptr) {
      let len = new Uint32Array(buffer)[ptr + SIZE_OFFSET >>> 2] >>> 1;
      const wtf16 = new Uint16Array(buffer, ptr, len);
      if (len <= STRING_SMALLSIZE) return String.fromCharCode(...wtf16);
      try {
        return utf16.decode(wtf16);
      } catch {
        let str = "", off = 0;
        while (len - off > STRING_CHUNKSIZE) {
          str += String.fromCharCode(...wtf16.subarray(off, off += STRING_CHUNKSIZE));
        }
        return str + String.fromCharCode(...wtf16.subarray(off));
      }
    }

    /** Prepares the base module prior to instantiation. */
    function preInstantiate(imports) {
      const extendedExports = {};

      function getString(memory, ptr) {
        if (!memory) return "<yet unknown>";
        return getStringImpl(memory.buffer, ptr);
      }

      // add common imports used by stdlib for convenience
      const env = (imports.env = imports.env || {});
      env.abort = env.abort || function abort(msg, file, line, colm) {
        const memory = extendedExports.memory || env.memory; // prefer exported, otherwise try imported
        throw Error(`abort: ${getString(memory, msg)} at ${getString(memory, file)}:${line}:${colm}`);
      };
      env.trace = env.trace || function trace(msg, n, ...args) {
        const memory = extendedExports.memory || env.memory;
        console.log(`trace: ${getString(memory, msg)}${n ? " " : ""}${args.slice(0, n).join(", ")}`);
      };
      env.seed = env.seed || Date.now;
      imports.Math = imports.Math || Math;
      imports.Date = imports.Date || Date;

      return extendedExports;
    }

    /** Prepares the final module once instantiation is complete. */
    function postInstantiate(extendedExports, instance) {
      const exports = instance.exports;
      const memory = exports.memory;
      const table = exports.table;
      const __new = exports.__new || F_NO_EXPORT_RUNTIME;
      const __pin = exports.__pin || F_NO_EXPORT_RUNTIME;
      const __unpin = exports.__unpin || F_NO_EXPORT_RUNTIME;
      const __collect = exports.__collect || F_NO_EXPORT_RUNTIME;
      const __rtti_base = exports.__rtti_base;
      const getRttiCount = __rtti_base ? arr => arr[__rtti_base >>> 2] : F_NO_EXPORT_RUNTIME;

      extendedExports.__new = __new;
      extendedExports.__pin = __pin;
      extendedExports.__unpin = __unpin;
      extendedExports.__collect = __collect;

      /** Gets the runtime type info for the given id. */
      function getRttInfo(id) {
        const U32 = new Uint32Array(memory.buffer);
        if ((id >>>= 0) >= getRttiCount(U32)) throw Error(`invalid id: ${id}`);
        return U32[(__rtti_base + 4 >>> 2) + (id << 1)];
      }

      /** Gets the runtime base id for the given id. */
      function getRttBase(id) {
        const U32 = new Uint32Array(memory.buffer);
        if ((id >>>= 0) >= getRttiCount(U32)) throw Error(`invalid id: ${id}`);
        return U32[(__rtti_base + 4 >>> 2) + (id << 1) + 1];
      }

      /** Gets and validate runtime type info for the given id for array like objects */
      function getArrayInfo(id) {
        const info = getRttInfo(id);
        if (!(info & (ARRAYBUFFERVIEW | ARRAY | STATICARRAY))) throw Error(`not an array: ${id}, flags=${info}`);
        return info;
      }

      /** Gets the runtime alignment of a collection's values. */
      function getValueAlign(info) {
        return 31 - Math.clz32((info >>> VAL_ALIGN_OFFSET) & 31); // -1 if none
      }

      /** Gets the runtime alignment of a collection's keys. */
      // function getKeyAlign(info) {
      //   return 31 - Math.clz32((info >>> KEY_ALIGN_OFFSET) & 31); // -1 if none
      // }

      /** Allocates a new string in the module's memory and returns its pointer. */
      function __newString(str) {
        if (str == null) return 0;
        const length = str.length;
        const ptr = __new(length << 1, STRING_ID);
        const U16 = new Uint16Array(memory.buffer);
        for (var i = 0, p = ptr >>> 1; i < length; ++i) U16[p + i] = str.charCodeAt(i);
        return ptr;
      }

      extendedExports.__newString = __newString;

      /** Allocates a new ArrayBuffer in the module's memory and returns its pointer. */
      function __newArrayBuffer(buf) {
        if (buf == null) return 0;
        const bufview = new Uint8Array(buf);
        const ptr = __new(bufview.length, ARRAYBUFFER_ID);
        const U8 = new Uint8Array(memory.buffer);
        U8.set(bufview, ptr);
        return ptr;
      }

      extendedExports.__newArrayBuffer = __newArrayBuffer;

      /** Reads a string from the module's memory by its pointer. */
      function __getString(ptr) {
        if (!ptr) return null;
        const buffer = memory.buffer;
        const id = new Uint32Array(buffer)[ptr + ID_OFFSET >>> 2];
        if (id !== STRING_ID) throw Error(`not a string: ${ptr}`);
        return getStringImpl(buffer, ptr);
      }

      extendedExports.__getString = __getString;

      /** Gets the view matching the specified alignment, signedness and floatness. */
      function getView(alignLog2, signed, float) {
        const buffer = memory.buffer;
        if (float) {
          switch (alignLog2) {
            case 2: return new Float32Array(buffer);
            case 3: return new Float64Array(buffer);
          }
        } else {
          switch (alignLog2) {
            case 0: return new (signed ? Int8Array : Uint8Array)(buffer);
            case 1: return new (signed ? Int16Array : Uint16Array)(buffer);
            case 2: return new (signed ? Int32Array : Uint32Array)(buffer);
            case 3: return new (signed ? BigInt64Array : BigUint64Array)(buffer);
          }
        }
        throw Error(`unsupported align: ${alignLog2}`);
      }

      /** Allocates a new array in the module's memory and returns its pointer. */
      function __newArray(id, valuesOrCapacity = 0) {
        const input = valuesOrCapacity;
        const info = getArrayInfo(id);
        const align = getValueAlign(info);
        const isArrayLike = typeof input !== "number";
        const length = isArrayLike ? input.length : input;
        const buf = __new(length << align, info & STATICARRAY ? id : ARRAYBUFFER_ID);
        let result;
        if (info & STATICARRAY) {
          result = buf;
        } else {
          __pin(buf);
          const arr = __new(info & ARRAY ? ARRAY_SIZE : ARRAYBUFFERVIEW_SIZE, id);
          __unpin(buf);
          const U32 = new Uint32Array(memory.buffer);
          U32[arr + ARRAYBUFFERVIEW_BUFFER_OFFSET >>> 2] = buf;
          U32[arr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2] = buf;
          U32[arr + ARRAYBUFFERVIEW_BYTELENGTH_OFFSET >>> 2] = length << align;
          if (info & ARRAY) U32[arr + ARRAY_LENGTH_OFFSET >>> 2] = length;
          result = arr;
        }
        if (isArrayLike) {
          const view = getView(align, info & VAL_SIGNED, info & VAL_FLOAT);
          const start = buf >>> align;
          if (info & VAL_MANAGED) {
            for (let i = 0; i < length; ++i) {
              view[start + i] = input[i];
            }
          } else {
            view.set(input, start);
          }
        }
        return result;
      }

      extendedExports.__newArray = __newArray;

      /** Gets a live view on an array's values in the module's memory. Infers the array type from RTTI. */
      function __getArrayView(arr) {
        const U32 = new Uint32Array(memory.buffer);
        const id = U32[arr + ID_OFFSET >>> 2];
        const info = getArrayInfo(id);
        const align = getValueAlign(info);
        let buf = info & STATICARRAY
          ? arr
          : U32[arr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2];
        const length = info & ARRAY
          ? U32[arr + ARRAY_LENGTH_OFFSET >>> 2]
          : U32[buf + SIZE_OFFSET >>> 2] >>> align;
        return getView(align, info & VAL_SIGNED, info & VAL_FLOAT).subarray(buf >>>= align, buf + length);
      }

      extendedExports.__getArrayView = __getArrayView;

      /** Copies an array's values from the module's memory. Infers the array type from RTTI. */
      function __getArray(arr) {
        const input = __getArrayView(arr);
        const len = input.length;
        const out = new Array(len);
        for (let i = 0; i < len; i++) out[i] = input[i];
        return out;
      }

      extendedExports.__getArray = __getArray;

      /** Copies an ArrayBuffer's value from the module's memory. */
      function __getArrayBuffer(ptr) {
        const buffer = memory.buffer;
        const length = new Uint32Array(buffer)[ptr + SIZE_OFFSET >>> 2];
        return buffer.slice(ptr, ptr + length);
      }

      extendedExports.__getArrayBuffer = __getArrayBuffer;

      /** Gets a function from poiner which contain table's index. */
      function __getFunction(ptr) {
        if (!table) throw Error(E_NO_EXPORT_TABLE);
        const index = new Uint32Array(memory.buffer)[ptr >>> 2];
        return table.get(index);
      }

      extendedExports.__getFunction = __getFunction;

      /** Copies a typed array's values from the module's memory. */
      function getTypedArray(Type, alignLog2, ptr) {
        return new Type(getTypedArrayView(Type, alignLog2, ptr));
      }

      /** Gets a live view on a typed array's values in the module's memory. */
      function getTypedArrayView(Type, alignLog2, ptr) {
        const buffer = memory.buffer;
        const U32 = new Uint32Array(buffer);
        return new Type(
          buffer,
          U32[ptr + ARRAYBUFFERVIEW_DATASTART_OFFSET >>> 2],
          U32[ptr + ARRAYBUFFERVIEW_BYTELENGTH_OFFSET >>> 2] >>> alignLog2
        );
      }

      /** Attach a set of get TypedArray and View functions to the exports. */
      function attachTypedArrayFunctions(ctor, name, align) {
        extendedExports[`__get${name}`] = getTypedArray.bind(null, ctor, align);
        extendedExports[`__get${name}View`] = getTypedArrayView.bind(null, ctor, align);
      }

      [
        Int8Array,
        Uint8Array,
        Uint8ClampedArray,
        Int16Array,
        Uint16Array,
        Int32Array,
        Uint32Array,
        Float32Array,
        Float64Array
      ].forEach(ctor => {
        attachTypedArrayFunctions(ctor, ctor.name, 31 - Math.clz32(ctor.BYTES_PER_ELEMENT));
      });

      if (BIGINT) {
        [BigUint64Array, BigInt64Array].forEach(ctor => {
          attachTypedArrayFunctions(ctor, ctor.name.slice(3), 3);
        });
      }

      /** Tests whether an object is an instance of the class represented by the specified base id. */
      function __instanceof(ptr, baseId) {
        const U32 = new Uint32Array(memory.buffer);
        let id = U32[ptr + ID_OFFSET >>> 2];
        if (id <= getRttiCount(U32)) {
          do {
            if (id == baseId) return true;
            id = getRttBase(id);
          } while (id);
        }
        return false;
      }

      extendedExports.__instanceof = __instanceof;

      // Pull basic exports to extendedExports so code in preInstantiate can use them
      extendedExports.memory = extendedExports.memory || memory;
      extendedExports.table  = extendedExports.table  || table;

      // Demangle exports and provide the usual utility on the prototype
      return demangle(exports, extendedExports);
    }

    function isResponse(src) {
      return typeof Response !== "undefined" && src instanceof Response;
    }

    function isModule(src) {
      return src instanceof WebAssembly.Module;
    }

    /** Asynchronously instantiates an AssemblyScript module from anything that can be instantiated. */
    async function instantiate(source, imports = {}) {
      if (isResponse(source = await source)) return instantiateStreaming(source, imports);
      const module = isModule(source) ? source : await WebAssembly.compile(source);
      const extended = preInstantiate(imports);
      const instance = await WebAssembly.instantiate(module, imports);
      const exports = postInstantiate(extended, instance);
      return { module, instance, exports };
    }

    /** Asynchronously instantiates an AssemblyScript module from a response, i.e. as obtained by `fetch`. */
    async function instantiateStreaming(source, imports = {}) {
      if (!WebAssembly.instantiateStreaming) {
        return instantiate(
          isResponse(source = await source)
            ? source.arrayBuffer()
            : source,
          imports
        );
      }
      const extended = preInstantiate(imports);
      const result = await WebAssembly.instantiateStreaming(source, imports);
      const exports = postInstantiate(extended, result.instance);
      return { ...result, exports };
    }

    /** Demangles an AssemblyScript module's exports to a friendly object structure. */
    function demangle(exports, extendedExports = {}) {
      const setArgumentsLength = exports["__argumentsLength"]
        ? length => { exports["__argumentsLength"].value = length; }
        : exports["__setArgumentsLength"] || exports["__setargc"] || (() => { /* nop */ });
      for (let internalName of Object.keys(exports)) {
        const elem = exports[internalName];
        let parts = internalName.split(".");
        let curr = extendedExports;
        while (parts.length > 1) {
          let part = parts.shift();
          if (!Object.hasOwn(curr, part)) curr[part] = {};
          curr = curr[part];
        }
        let name = parts[0];
        let hash = name.indexOf("#");
        if (hash >= 0) {
          const className = name.substring(0, hash);
          const classElem = curr[className];
          if (typeof classElem === "undefined" || !classElem.prototype) {
            const ctor = function(...args) {
              return ctor.wrap(ctor.prototype.constructor(0, ...args));
            };
            ctor.prototype = {
              valueOf() { return this[THIS]; }
            };
            ctor.wrap = function(thisValue) {
              return Object.create(ctor.prototype, { [THIS]: { value: thisValue, writable: false } });
            };
            if (classElem) Object.getOwnPropertyNames(classElem).forEach(name =>
              Object.defineProperty(ctor, name, Object.getOwnPropertyDescriptor(classElem, name))
            );
            curr[className] = ctor;
          }
          name = name.substring(hash + 1);
          curr = curr[className].prototype;
          if (/^(get|set):/.test(name)) {
            if (!Object.hasOwn(curr, name = name.substring(4))) {
              let getter = exports[internalName.replace("set:", "get:")];
              let setter = exports[internalName.replace("get:", "set:")];
              Object.defineProperty(curr, name, {
                get() { return getter(this[THIS]); },
                set(value) { setter(this[THIS], value); },
                enumerable: true
              });
            }
          } else {
            if (name === 'constructor') {
              (curr[name] = function(...args) {
                setArgumentsLength(args.length);
                return elem(...args);
              }).original = elem;
            } else { // instance method
              (curr[name] = function(...args) { // !
                setArgumentsLength(args.length);
                return elem(this[THIS], ...args);
              }).original = elem;
            }
          }
        } else {
          if (/^(get|set):/.test(name)) {
            if (!Object.hasOwn(curr, name = name.substring(4))) {
              Object.defineProperty(curr, name, {
                get: exports[internalName.replace("set:", "get:")],
                set: exports[internalName.replace("get:", "set:")],
                enumerable: true
              });
            }
          } else if (typeof elem === "function" && elem !== setArgumentsLength) {
            (curr[name] = (...args) => {
              setArgumentsLength(args.length);
              return elem(...args);
            }).original = elem;
          } else {
            curr[name] = elem;
          }
        }
      }
      return extendedExports;
    }

    function readAssembly() {
        if (globalThis.atob) {
            var source = globalThis.atob(wasm);
            var sourceLength = source.length;
            var bytes = new Uint8Array(sourceLength);
            for (var i = 0; i < sourceLength; i++) {
                bytes[i] = source.charCodeAt(i);
            }
            return bytes.buffer;
        }
        else {
            return Buffer.from(wasm, 'base64');
        }
    }
    var buffer;
    var Buffer$1 = {
        init: function () {
            return __awaiter(this, void 0, void 0, function () {
                return __generator(this, function (_a) {
                    switch (_a.label) {
                        case 0:
                            if (buffer)
                                return [2 /*return*/, buffer];
                            return [4 /*yield*/, instantiate(readAssembly())];
                        case 1: return [2 /*return*/, (buffer = (_a.sent()).exports)];
                    }
                });
            });
        }
    };

    /**
     * @module examples
     */
    var raf;
    var index = 0;
    var start = document.getElementById('start');
    var stop = document.getElementById('stop');
    var view = document.getElementById('view');
    function onStart() {
        onStop();
        Buffer$1.init().then(function (_a) {
            var Buffer = _a.Buffer, __newString = _a.__newString, __getUint8Array = _a.__getUint8Array;
            var timeStamp = window.performance.now();
            var buffer = new Buffer();
            buffer.write(__newString("".concat(++index, ": A buffer tool using WebAssembly.")));
            var performance = window.performance.now() - timeStamp;
            view.value = "".concat(hex(__getUint8Array(buffer.bytes)), "\r\n\r\nperformance: ").concat(performance, "ms");
            raf = window.requestAnimationFrame(onStart);
        });
    }
    function onStop() {
        window.cancelAnimationFrame(raf);
    }
    start.addEventListener('click', onStart, false);
    stop.addEventListener('click', onStop, false);

}));
